README.md, iceoryx_examples/README.md
- Fix Debian release link
- Fix example links $ROOT/README.md
- Fix typo in $ROOT/README.md "Great that your still here"
- Fix typo in $ROOT/README.md "./tools/iceoryx_build - test.sh
- Fix description for examples $ROOT/iceoryx_examples/README.md
Signed-off-by: Hoinkis Simon (CC-AD/ESW1) <simon.hoinkis2@de.bosch.com>
=> [IOX#3] Fix typos, repair links and comment-out Debian package usage

iceoryx_examples/icedelivery/CMakeLists.txt, iceoryx_examples/icedelivery/README.md, iceoryx_examples/icedelivery/a_typed_api.hpp, iceoryx_examples/icedelivery/ice_receiver.cpp, iceoryx_examples/icedelivery/ice_receiver_simple.cpp, iceoryx_examples/icedelivery/ice_sender.cpp, iceoryx_examples/icedelivery/ice_sender_simple.cpp, iceoryx_posh/CMakeLists.txt, iceoryx_posh/cmake/iceoryx_versions.hpp.in, iceoryx_posh/cmake/iceoryxversions.cmake, iceoryx_posh/include/iceoryx_posh/internal/popo/receiver_port_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl, iceoryx_posh/include/iceoryx_posh/internal/runtime/runnable_data.hpp, iceoryx_posh/include/iceoryx_posh/mepoo/mepoo_config.hpp, iceoryx_posh/include/iceoryx_posh/popo/gateway_discovery.hpp, iceoryx_posh/include/iceoryx_posh/popo/gateway_generic.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp, iceoryx_posh/source/mepoo/mepoo_config.cpp, iceoryx_posh/source/popo/base_port.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_utils/CMakeLists.txt, iceoryx_utils/cmake/IceoryxPackageHelper.cmake, tools/iceoryx_build_test.sh
fixes https://github.com/eclipse/iceoryx/issues/5
as per title. There are a bunch of trailing whitespaces in iceoryx at the moment.
Signed-off-by: Knese Karsten <karsten.knese@us.bosch.com>
=> whitespace cleanup

README.md, tools/docker/.screenrc, tools/docker/Dockerfile, tools/docker/README.md, tools/docker/build_and_run.sh
This adds a Docker environment for building and running iceoryx applications as described in #15.
It suggests a usage pattern based on `docker exec` and one based on `screen`, depending on preference and configuration.
Further details are on the description of related issue #15 and inside the added documentation files.
Thanks for your kind feedback!
=> Iox #15 add docker environment

README.md, iceoryx_posh/source/popo/subscriber.cpp, iceoryx_utils/include/iceoryx_utils/fixed_string/string100.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.inl, iceoryx_utils/include/iceoryx_utils/internal/cxx/vector.inl, iceoryx_utils/include/iceoryx_utils/internal/file_reader/file_reader.hpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/access_control.hpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object.hpp, iceoryx_utils/source/file_reader/file_reader.cpp, iceoryx_utils/source/fixed_string/string100.cpp, iceoryx_utils/source/posix_wrapper/access_control.cpp, iceoryx_utils/source/posix_wrapper/shared_memory_object.cpp
1. Make subscriber thread name shorter to prevent truncation of format string
2. Replace use of ushort, uint with more explicit types
3. Use default destructors where appropriate
4. Use std::cerr instead of fprintf
5. Make ACL enum classes extend actual underlying numeric types
6. Use std::remove_pointer<acl_t>:: type instead of implementation-dependent __acl_ext
7. Switch instructions from apt-get to the more friendly apt
=> Minor cleanups

iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/access_control.hpp
the ACL types on QNX are different from the ones on linux, therefore this conditional compilation for the AccessController enums
=> fix qnx build

README.md, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl, iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.inl, iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_creator.inl, iceoryx_posh/source/mepoo/memory_manager.cpp, iceoryx_utils/CMakeLists.txt, iceoryx_utils/include/iceoryx_utils/cxx/convert.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/convert.inl, iceoryx_utils/source/posix_wrapper/shared_memory_object/allocator.cpp, iceoryx_utils/source/units/duration.cpp, iceoryx_utils/test/moduletests/test_cxx_convert.cpp, iceoryx_utils/test/moduletests/test_objectpool.cpp
- fixed alignment problems in 32-bit mode
- duration rounding error in 32-bit fixed
- objectpool bug fixed which occurred only in 32-bit
- convert support for long long (unsigned) int is gone since long long cannot be supported in 32-bit
- 32-bit problems im memory management solved
Signed-off-by: Eltzschig Christian (CC-AD/ESW1) <christian.eltzschig2@de.bosch.com>
=> IOX-#12 32-bit support - fixing alignment problem

cmake/cpptoml/CMakeLists.txt, iceoryx_posh/source/runtime/posh_runtime.cpp, iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relocatable_ptr.hpp, iceoryx_utils/test/moduletests/test_relative_pointer.cpp
=> iox-#43 fix clang build

PLANNED_FEATURES.md, README.md
Kudos to @marthtz and @GerdHirsch for helping to create the idea for the GIF!
=> IOX-#36 Add teaser GIF to Readme and update planned features

iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp, iceoryx_utils/source/posix_wrapper/timer.cpp
Thanks, Clang!
```
--- stderr: iceoryx_utils
In file included from /opt/ros/master/src/eclipse/iceoryx/iceoryx_utils/source/posix_wrapper/timer.cpp:15:
/opt/ros/master/src/eclipse/iceoryx/iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp:87:59: warning: result of '2 ^ 24' is 26; did you mean '1 << 24' (16777216)? [-Wxor-used-as-pow]
static constexpr uint32_t MAX_DESCRIPTOR_VALUE{(2 ^ 24) - 1};
~~^~~~
1 << 24
/opt/ros/master/src/eclipse/iceoryx/iceoryx_utils/include/iceoryx_utils/posix_wrapper/timer.hpp:87:59: note: replace expression with '0x2 ^ 24' or use 'xor' instead of '^' to silence this warning
1 warning generated.
```
=> Fix operator mistake

tools/introspection/source/introspection_app.cpp
```
/opt/ros/master/src/eclipse/iceoryx/tools/introspection/source/introspection_app.cpp:244:90: error: cannot pass object of non-trivial type 'const cxx::CString100' through variadic function; call will abort at runtime [-Wnon-pod-varargs]
wprintw(pad, "PID: %*d Process: %*s\n", pidWidth, data.m_pid, processWidth, data.m_name);
^
1 error generated.
make[2]: *** [CMakeFiles/iceoryx_introspection.dir/source/introspection_app.cpp.o] Error 1
make[1]: *** [CMakeFiles/iceoryx_introspection.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< iceoryx_introspection	[ Exited with code 2 ]
```
=> Fix variadic function build warning

iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl
allocateChunk should return nullptr if chunkHeader==nullptr, or it might cause some problem in returning chunkHeader->payload() and user can't check whether allocate chunk successfully or not.
=> Fix chunkHeader==nullptr in allocateChunk

.github/workflows/build-test.yml
Add github workflow to build & test iceoryx. (There is an additional build action to build with clang compiler)
This workflow is triggered on push to master or pull request events but only for the master branch.
The job defined in the workflow can be used as a check for PR
closes #89
=> iox-#89 add github workflow for build & test

iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
=> iox-#110 increase PROCESS_WAITING_FOR_ROUDI_TIMEOUT to 60s

iceoryx_utils/source/posix_wrapper/message_queue.cpp, iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_utils/test/moduletests/test_message_queue.cpp
=> iox-#150 fix-destroy-method-of-message-queue-and-unix-domain-socket

iceoryx_posh/source/popo/building_blocks/chunk_receiver.cpp
Signed-off-by: Christian Eltzschig <christian.eltzschig2@de.bosch.com>
=> iox-#157: fixed syntax error by adding a const cast

iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.hpp, iceoryx_posh/source/popo/building_blocks/chunk_queue_popper.cpp, iceoryx_posh/source/popo/ports/subscriber_port_multi_producer.cpp, iceoryx_posh/source/popo/ports/subscriber_port_user.cpp
It seems there was a merge which introduced warnings and the merge of #164 master is now broken
=> iox-#153 fix master after merge of setting -Werror for CI

iceoryx_posh/include/iceoryx_posh/roudi/iceoryx_roudi_components.hpp, iceoryx_posh/include/iceoryx_posh/roudi/roudi_app.hpp, iceoryx_posh/source/popo/building_blocks/chunk_queue_popper.cpp, iceoryx_posh/source/popo/building_blocks/chunk_receiver.cpp, iceoryx_posh/source/roudi/application/roudi_main.cpp, iceoryx_posh/source/runtime/message_queue_interface.cpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl, iceoryx_utils/include/iceoryx_utils/internal/cxx/optional.inl, iceoryx_utils/source/posix_wrapper/shared_memory_object/allocator.cpp, iceoryx_utils/test/moduletests/test_cxx_expected.cpp, iceoryx_utils/test/moduletests/test_cxx_optional.cpp
=> Iox #160 optional and expected adjustments

tools/introspection/CMakeLists.txt
fixes #175 
`ncurses` is available through `homebrew`, however `tinfo` isn't - It is also not needed though.
How did you test this in the past? I couldn't really find a way to make `tinfo` available on OSX.
=> make introspection compile on OSX

iceoryx_utils/README.md, iceoryx_utils/include/iceoryx_utils/cxx/string.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/string.inl, iceoryx_utils/test/moduletests/test_cxx_string.cpp
=> iox-#264 fix char array assignment to cxx::string

.codecov.yml, iceoryx_posh/source/roudi/roudi_process.cpp
Signed-off-by: Hintz Martin (CC-AD/ESW1) <martin.hintz@de.bosch.com>
=> iox-#271: Fix name clash

iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.inl
Indexing of the ring buffer of the SOFI was done by casting to an int32_t and then taking the modulo of the size. This resulted in a wrong index after 2^31 push/pop operations.
The bug was unveiled by running #115 with a stress time of 15 minutes.
Closes #289 
=> iox-#289 fix SOFI ring buffer indexing

iceoryx_utils/test/CMakeLists.txt, iceoryx_utils/test/stresstests/test_stress_sofi.cpp
closes #115 
Initially, all atomic counter where accessed with memory_order_seq_cst. In order to not synchronize with the counter, I used different orderings, but I'm not sure if this is a good idea since there is a good chance that the ordering is wrong. Do you think I should change it back? In this case we would just stresstest the algorithm without checking the memory order.
@dkroenke, do we want to have one binary per stresstest?
=> Iox #115 add sofi stresstests

cpptoml_vendor/CMakeLists.txt
When compiling with Clang (note, not apple-clang) there's some option within the cpptoml cmake phase. These have to exposed in the vendor package as well.
=> expose cmake options in cpptoml vendor package

CONTRIBUTING.md, doc/conceptual-guide.md, doc/error-handling.md
Recreated previous pull request https://github.com/eclipse/iceoryx/pull/317 on error handling concept (which will then be obsolete).
Corrected typos and examples.
Added section about exception handling.
Clearly distinguish between current state and potential future extension/improvements, added Future Improvements section for this purpose.
Added link from  Contributions.md file.
=> Iox #313 document error handling

iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp, iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp, iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp, iceoryx_utils/include/iceoryx_utils/cxx/expected.hpp, iceoryx_utils/include/iceoryx_utils/cxx/optional.hpp, iceoryx_utils/include/iceoryx_utils/cxx/unique_ptr.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl, iceoryx_utils/include/iceoryx_utils/internal/cxx/unique_ptr.inl, iceoryx_utils/test/moduletests/test_cxx_expected.cpp
* adds an `and_then` specialization for `cxx::expected<cxx::optional<T>>` that automatically retrieves the value from non-empty optionals
* the and_then specialization does nothing if the optional is empty
* adds `if_empty()` method to `cxx::expected<cxx::optional<T>>` types that allows users to react to retrieving an empty optional without error
=> Iox #340 simplify expected optionals

README.md
Instead of manually keeping the maintainer list up to date, just link the the Eclipse project page
closes #366 
Signed-off-by: Mathias Kraus <mathias.kraus@apex.ai>
=> iox-#366 update maintainer list

.github/workflows/colcon.yml
fix Warning in CI colcon build (github action) by updating Ros toolchain to `ros-tooling/setup-ros@0.0.26`
Warning was:
```
@github-actions github-actions / build (ubuntu-20.04)
The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Signed-off-by: bishibashiB <b.eickhoff@gmx.de>
=> iox-#328 update to ros-tooling/setup-ros@0.0.26

iceoryx_posh/include/iceoryx_posh/mepoo/segment_config.hpp, iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/access_control.hpp, iceoryx_utils/include/iceoryx_utils/posix_wrapper/posix_access_rights.hpp, iceoryx_utils/source/posix_wrapper/posix_access_rights.cpp, iceoryx_utils/test/moduletests/test_access_control.cpp
First part on the journey to remove std::string from the utils
partly closes #260 
Signed-off-by: Mathias Kraus <mathias.kraus@apex.ai>
=> iox-#260 remove std::string from PosixAccessRights, AccessControl and SegmentConfig

iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/base_publisher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/modern_api/base_subscriber.inl, iceoryx_posh/include/iceoryx_posh/popo/modern_api/base_publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/modern_api/base_subscriber.hpp, iceoryx_posh/test/mocks/publisher_mock.hpp, iceoryx_posh/test/mocks/subscriber_mock.hpp, iceoryx_posh/test/moduletests/test_popo_base_publisher.cpp, iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp
Addressing the port memory leak - ports will now be automatically destroyed when publishers or subscribers are destructed.
We can discuss further in #369 if we need to do anything else to resolve it.
Signed-off-by: Ithier Jeff (CC-AD/EYF1) <jeff.ithier@de.bosch.com>
=> iox-#369 Destroy underlying ports when pubsub entities are destructed.

cmake/cyclonedds/CMakeLists.txt, cmake/cyclonedds/cyclonedds-cxx.cmake.in, iceoryx_dds/CMakeLists.txt, iceoryx_dds/cmake/idlpp-cxx-generate.cmake.in
As the title explains, the Cyclone DDS C++ API now has an official repository on github.
This PR updates the build to fetch the source from there.
=> iox-#376 Fetch C++ Cyclone DDS library from official repo.

iceoryx_binding_c/include/iceoryx_binding_c/runnable.h, iceoryx_binding_c/include/iceoryx_binding_c/runtime.h, iceoryx_binding_c/source/c_runnable.cpp, iceoryx_binding_c/source/c_runtime.cpp, iceoryx_binding_c/test/integrationtests/test_runnable.cpp, iceoryx_binding_c/test/integrationtests/test_runtime.cpp, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi_environment/roudi_environment.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi_environment/runtime_test_interface.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime_single_process.hpp, iceoryx_posh/source/capro/service_description.cpp, iceoryx_posh/source/roudi_environment/roudi_environment.cpp, iceoryx_posh/source/roudi_environment/runtime_test_interface.cpp, iceoryx_posh/source/runtime/posh_runtime.cpp, iceoryx_posh/source/runtime/posh_runtime_single_process.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp
This PR removes the std::string from the RouDiEnvironment and from the public API from PoshRuntime.
The C binding is adjusted and some bugs were fixed
partly closes #260
=> Iox #260 remove std string from posh part 1

iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl, iceoryx_posh/source/popo/receiver_port_data.cpp, iceoryx_posh/source/popo/sender_port_data.cpp, iceoryx_posh/source/roudi/port_pool.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp, iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp
This PR removes the std::string usage from the PortIntrospection.
Instead of serializing the ServiceDescription to use it as a key for some std::maps, the ServiceDescription is now used itself as key.
1. [x] All …
=> Iox #260 remove std string from introspection and use correct ProcessName_t alias everywhere

iceoryx_posh/source/popo/wait_set.cpp
This changes the behavior of the waitset back to how it was originally. The `wait` call returns immediately if there are chunks in the queue of a subscriber. I.e. it is a "there is some work todo" waitset. Another …
=> iox-#388 fixed waitset behavior back to "there are samples in the queue"

iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_process.hpp
Within the attached source std::list usage was removed from roudi process list handling (replaced with cxx::list implementation).
Additionally the FixedPositionContainer of roudi port pool was picked to replace with cxx::list as well... see details in #221. (fixes #221)
This PR requires cxx::list to be approved (merged) #215 first.
=> Iox #221 apply cxx list

iceoryx_binding_c/source/c_runtime.cpp, iceoryx_dds/source/dds2iceoryx_app/main.cpp, iceoryx_dds/source/iceoryx2dds_app/main.cpp, iceoryx_examples/icedelivery/README.md, iceoryx_examples/icedelivery/ice_publisher_bare_metal.cpp, iceoryx_examples/icedelivery/ice_publisher_simple.cpp, iceoryx_examples/icedelivery/ice_subscriber_bare_metal.cpp, iceoryx_examples/icedelivery/ice_subscriber_simple.cpp, iceoryx_examples/icedelivery/iox_publisher_typed_modern.cpp, iceoryx_examples/icedelivery/iox_publisher_untyped_modern.cpp, iceoryx_examples/icedelivery/iox_subscriber_typed_modern.cpp, iceoryx_examples/icedelivery/iox_subscriber_untyped_modern.cpp, iceoryx_examples/iceperf/README.md, iceoryx_examples/iceperf/iceperf_hardy.cpp, iceoryx_examples/iceperf/iceperf_laurel.cpp, iceoryx_examples/waitset/ice_publisher_waitset.cpp, iceoryx_examples/waitset/ice_subscriber_waitset.cpp, iceoryx_posh/include/iceoryx_posh/internal/roudi_environment/runtime_test_interface.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/source/roudi_environment/runtime_test_interface.cpp, iceoryx_posh/source/runtime/posh_runtime.cpp, iceoryx_posh/source/runtime/posh_runtime_single_process.cpp, iceoryx_posh/test/integrationtests/service_discovery/test_roudi_findservice.cpp, iceoryx_posh/test/integrationtests/test_interface_port_stack_blowup.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, tools/introspection/source/introspection_app.cpp
This PR removes the default parameter from PoshRuntime::getInstance(). Therefore two new functions are introduced: 
getInstance without parameter to receive the active runtime and initRuntime to create the runtime
1. [x] All open points are addressed and tracked via …
=> Iox #382 remove default param from getInstance

iceoryx_posh/doc/chunk_header.md
This is a test for a workflow with a design document PR before a full implementation.
It's the first PR for a custom extension to the chunk header as requested by @rex-schilasky and also needed for the request response feature #27.
I would like to start implementing this …
=> iox-#14 chunk header design with custom header

iceoryx_binding_c/source/c_publisher.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_binding_c/test/moduletests/test_trigger_state.cpp, iceoryx_binding_c/test/moduletests/test_user_trigger.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, iceoryx_examples/icedelivery_on_c/README.md, iceoryx_examples/waitset_on_c/README.md, iceoryx_examples/waitset_on_c/ice_c_waitset_gateway.c, iceoryx_examples/waitset_on_c/ice_c_waitset_grouping.c, iceoryx_examples/waitset_on_c/ice_c_waitset_individual.c, iceoryx_examples/waitset_on_c/ice_c_waitset_publisher.c, iceoryx_examples/waitset_on_c/ice_c_waitset_sync.c, iceoryx_posh/CMakeLists.txt, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_variable_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp, iceoryx_posh/source/popo/building_blocks/condition_variable_data.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/port_pool.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_posh/test/moduletests/test_popo_base_subscriber.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp, iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp, iceoryx_posh/test/moduletests/test_popo_trigger.cpp, iceoryx_posh/test/moduletests/test_popo_trigger_handle.cpp, iceoryx_posh/test/moduletests/test_popo_user_trigger.cpp, iceoryx_posh/test/moduletests/test_popo_waitset.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
1. [ ] Branch follows the naming format (`iox-#123-this-is-a-branch`)
1. [ ] Commits messages are according to this [guideline][commit-guidelines]
1. [ ] Update the PR title
1. [ ] Relevant issues are linked
1. [ ] Add sensible notes for the reviewer
1. [ ] All checks have passed
1. [ ] Assign PR to reviewer
1. [ ] Merge
- see #341
=> iox-#341 implemented condition variable cleanup in waitset destructor

iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp
=> iox-#447 fix seg fault in roudi

iceoryx_utils/testutils/mocks/mocks.hpp, iceoryx_utils/testutils/mocks/mqueue_mock.cpp, iceoryx_utils/testutils/mocks/time_mock.cpp
Signed-off-by: Hintz Martin (CC-AD/ESW1) <martin.hintz@de.bosch.com>
Adding an on demand function loader for system function mocks. This fixes #427.
To reproduce the error, apply the patch file included in the bug issue to iceoryx/master and run MqMessage_test. You can …
=> iox-#427 Add on demand function loader for system function mocks

iceoryx_utils/include/iceoryx_utils/internal/relocatable_pointer/relative_ptr.hpp, iceoryx_utils/test/moduletests/test_relative_pointer.cpp
1. Fix 1: Base c'tor/ operator `=` is called instead of `computeOffset()`. This fixes #431.
1. Fix 2: `const void` was not supported as type. Removed the specialized template and using a SFINAE approach now. Added a test for this as well.
3. I don't like the naming. Why …
=> Iox #431 iox::relative_ptr takes invalid state when constructed/assigned from iox::RelativePointer

iceoryx_posh/test/moduletests/test_roudi_memory_block.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
code contributed by @JimmyBch
1. [ ] Merge
- partly closes #454
=> iox-#454 improve coverage of class roudi memory provider, memory block and memory manager

iceoryx_binding_c/source/cpp2c_enum_translation.cpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/moduletests/test_roudi_process.cpp
@BH1SCW This is the PR for compiling iceoryx on GCC 5.4, please check out if it works on your side. Please note that i installed manually a newer CMake version on Ubuntu 16 for building.
- add namespace to SubscribeState in C-Binding
- initialize NodeName_t in …
=> Iox #495 compile iceoryx on gcc 5

iceoryx_binding_c/source/c_user_trigger.cpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.inl, iceoryx_posh/include/iceoryx_posh/popo/user_trigger.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/source/popo/user_trigger.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp, iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp, iceoryx_posh/test/moduletests/test_roudi_process_introspection.cpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.inl, iceoryx_utils/test/moduletests/test_concurrent_periodic_task.cpp
This PR replaces the thread in the introspection classes with a `PeriodicTask` and simplifies the code. The test time with the RouDiEnvironment will also be reduced a little bit (1s posh_modultetests and 2s in posh_integrationtests), since the stopping of the threads is …
=> Iox #489 replace introspection threads with periodic task

.github/workflows/build-test.yml, .github/workflows/colcon.yml, .github/workflows/coverage_doc.yml, .github/workflows/sanitize.yml
According to the current https://www.ros.org/reps/rep-2000.html for ROS2 Foxy and Galactic is MacOS Mojave (10.14) needed.
We can tie the MacOS runners to that version, same with Windows. 
1. [x] All checkboxes …
=> Iox #494 set MacOS Mojave in GitHub CI

iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_gw_gateway_discovery.cpp, iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp, iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp, iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl, iceoryx_utils/source/posix_wrapper/timer.cpp, iceoryx_utils/source/units/duration.cpp, iceoryx_utils/test/moduletests/test_cxx_deadline_timer.cpp, iceoryx_utils/test/moduletests/test_ipc_channel.cpp, iceoryx_utils/test/moduletests/test_posix_timer.cpp, iceoryx_utils/test/moduletests/test_semaphore_module.cpp, iceoryx_utils/test/moduletests/test_unit_duration.cpp, iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark.hpp, tools/introspection/source/introspection_app.cpp
This replaces the `long double` internal representation of `units::Duration` with `uint64_t` for seconds and `uint32_t` for nanoseconds.
1. [ ] …
=> Iox #190 fixed point types for duration internal representation

doc/website/getting-started/installation.md
Signed-off-by: Fanjun Kong <bh1scw@gmail.com>
1. [x] Merge
- Closes **TBD**
Fixes #533"
=> iox-#533 Add Installation guide after building.

iceoryx_binding_c/source/c_wait_set.cpp, iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/mempool_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp, iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp, iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/periodic_task.hpp, iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp, iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl, iceoryx_utils/source/posix_wrapper/timer.cpp, iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_utils/test/moduletests/test_cxx_deadline_timer.cpp, iceoryx_utils/test/moduletests/test_posix_timer.cpp, iceoryx_utils/test/moduletests/test_semaphore_module.cpp, iceoryx_utils/test/moduletests/test_unit_duration.cpp, iceoryx_utils/test/stresstests/benchmark_optional_and_expected/benchmark.hpp, tools/introspection/source/introspection_app.cpp
Signed-off-by: enkeyz <klarnorbert@gmail.com>
Refactored creation/getter method names to be more meaningful for "units::Duration". Partly closes: https://github.com/eclipse-iceoryx/iceoryx/issues/536
1. [ ] All …
=> iox-#536 refactored creation/getter method names in units::Duration

CONTRIBUTING.md, doc/website/advanced/best-practice-for-testing.md, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_utils/test/moduletests/test_unit_duration.cpp
This PR tries to document the our best practices to write tests for iceoryx. Some of them were unwritten, making it hard for new contributor to write test the way we expect it.
I still have to write a small example for typed and parameterized test, but this will be more …
=> Iox #521 best practice for testing

iceoryx_posh/source/runtime/message_queue_interface.cpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/unix_domain_socket.hpp, iceoryx_utils/source/posix_wrapper/unix_domain_socket.cpp
* Remove noisy output in `UnixDomainSocket`
* Loop till the `IpcChannelSide::Server` is created, this allows users to be able to start publisher and subscribers before RouDi is started
* Fix two resource leaks by introducting `closeFd(..)`
1. [x] All open points are …
=> Iox #381 Fix flooding the command line and resource leak

iceoryx_dds/test/mocks/google_mocks.hpp, iceoryx_dds/test/moduletests/test_dds_to_iox.cpp, iceoryx_dds/test/moduletests/test_iox_to_dds.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/sample.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/popo/sample.hpp, iceoryx_posh/test/moduletests/test_popo_sample.cpp
In order to add the custom chunk header to the typed publisher and subscriber, the `Sample` must also get an additional template parameter for the custom chunk header type. By default this must be `void`, to keep the current behavior. The …
=> iox-#14 Prepare sample for custom chunk header

iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl, iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
Signed-off-by: Hintz Martin (XC-AD/ESW1-J1) <martin.hintz@de.bosch.com> …
=> iox-#591 Added void_t to type_traits

iceoryx_examples/icecrystal/Readme.md, tools/introspection/source/introspection_app.cpp
=> Iox #349 add subscriber process to introspection

iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser.cpp, iceoryx_posh/test/moduletests/test_roudi_cmd_line_parser_config_file_option.cpp
Adding some more tests to test_roudi_cmd_line_parser_config_file_option. Code contributed by @JimmyBch .
1. [x] …
=> Iox #454 enhance cmd line parser tests

iceoryx_utils/include/iceoryx_utils/posix_wrapper/file_lock.hpp
=> iox-#625 set file lock directory to /tmp/

iceoryx_binding_c/include/iceoryx_binding_c/chunk.h, iceoryx_binding_c/include/iceoryx_binding_c/types.h, iceoryx_binding_c/source/c_chunk.cpp, iceoryx_binding_c/test/moduletests/test_chunk.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl, iceoryx_dds/test/mocks/chunk_mock_dds.hpp, iceoryx_examples/waitset/ice_waitset_gateway.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/chunk_header.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/publisher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/sample_deleter.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/sample_deleter.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher.inl, iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp, iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/untyped_publisher.hpp, iceoryx_posh/source/mepoo/chunk_header.cpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_posh/test/mocks/chunk_mock.hpp, iceoryx_posh/test/mocks/subscriber_mock.hpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
=> Iox #14 restrict access to chunk header

iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/roudi/roudi.cpp
1. [x] All required checks have passed (except `task-list-completed`) …
=> iox-#615 unblock RouDi shutdown with blocked publisher

iceoryx_utils/package.xml
This library is used here: https://github.com/eclipse-iceoryx/iceoryx/blob/c4270c988e06619f5db040a59a56f4f9449637a4/iceoryx_utils/CMakeLists.txt#L187-L189
Here are the backing rosdep rules for `libatomic`: https://github.com/ros/rosdistro/blob/master/rosdep/base.yaml#L1856-L1861
The library is somehow implicitly installed for our Ubuntu builds, but it needs an explicit dependency for RHEL: https://build.ros2.org/job/Rbin_rhel_el864__iceoryx_utils__rhel_8_x86_64__binary/5/console
=> Declare dependency on libatomic in package.xml

iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp, iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp, iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp, iceoryx_posh/test/mocks/subscriber_mock.hpp
=> Iox #714 call reset in subscriber destructor

.gitignore, doc/website/advanced/iceoryx_utils.md, doc/website/getting-started/examples/callbacks.md, doc/website/getting-started/examples/callbacks_in_c.md, doc/website/getting-started/examples/ice_access_control.md, doc/website/getting-started/examples/icecrystal.md, doc/website/getting-started/examples/icedelivery.md, doc/website/getting-started/examples/icedelivery_in_c.md, doc/website/getting-started/examples/iceensemble.md, doc/website/getting-started/examples/icehello.md, doc/website/getting-started/examples/iceoptions.md, doc/website/getting-started/examples/iceperf.md, doc/website/getting-started/examples/index.md, doc/website/getting-started/examples/singleprocess.md, doc/website/getting-started/examples/waitset.md, doc/website/getting-started/examples/waitset_in_c.md, doc/website/index.md, iceoryx_utils/README.md, mkdocs.yml, tools/export-docu-to-website.sh, tools/website/export-docu-to-website.sh
=> Iox #743 Fix website generation and typos

doc/website/getting-started/examples/complexdata.md, iceoryx_examples/README.md, iceoryx_examples/complexdata/CMakeLists.txt, iceoryx_examples/complexdata/README.md, iceoryx_examples/complexdata/iox_publisher_complexdata.cpp, iceoryx_examples/complexdata/iox_publisher_vector.cpp, iceoryx_examples/complexdata/iox_subscriber_complexdata.cpp, iceoryx_examples/complexdata/iox_subscriber_vector.cpp, iceoryx_examples/complexdata/topic_data.hpp, iceoryx_integrationtest/CMakeLists.txt, iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py, iceoryx_meta/CMakeLists.txt, iceoryx_utils/include/iceoryx_utils/cxx/variant.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/variant.inl, tools/iceoryx_build_test.sh
=> Iox #482 add example for complex data types

iceoryx_utils/include/iceoryx_utils/internal/cxx/variant.inl
linked to iox-#759 
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#co …
=> Iox #759 improve helix qac parsing coverage

.github/workflows/sanitize.yml
=> iox-#736 Use clang-10 in Github CI Sanitize workflow

.clang-tidy, .github/workflows/build-test.yml, iceoryx_examples/waitset/ice_waitset_basic.cpp, iceoryx_hoofs/cmake/IceoryxPlatform.cmake, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/platform/win/source/semaphore.cpp, iceoryx_hoofs/source/posix_wrapper/mutex.cpp, iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp, iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
=> iox-#33 posix mutex support in windows

iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
=> iox-#654 stop flooding output if there is an outdated socket

cmake/googletest/CMakeLists.txt, iceoryx_examples/iceperf/mq.cpp, iceoryx_examples/iceperf/uds.cpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp, iceoryx_hoofs/source/posix_wrapper/file_lock.cpp, iceoryx_hoofs/source/posix_wrapper/message_queue.cpp, iceoryx_hoofs/source/posix_wrapper/mutex.cpp, iceoryx_hoofs/source/posix_wrapper/semaphore.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp, iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp, iceoryx_posh/source/roudi/process_manager.cpp
=> Iox #805 enhance posix call

.github/workflows/build-test.yml, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/test/moduletests/test_posix_thread.cpp, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
=> Iox #33 relative pointer & posix threads for windows

iceoryx_examples/iceperf/uds.cpp, iceoryx_examples/waitset/ice_waitset_basic.cpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/ipc_channel.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/message_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp, iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/socket.hpp, iceoryx_hoofs/platform/linux/source/socket.cpp, iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/socket.hpp, iceoryx_hoofs/platform/mac/source/socket.cpp, iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/socket.hpp, iceoryx_hoofs/platform/qnx/source/socket.cpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/socket.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/time.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/windows.hpp, iceoryx_hoofs/platform/win/source/socket.cpp, iceoryx_hoofs/source/posix_wrapper/message_queue.cpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp, iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp, iceoryx_posh/source/capro/service_description.cpp, iceoryx_posh/source/runtime/ipc_interface_base.cpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
=> Iox #33 implement tests for unix domain socket

iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_collection_memory_block.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/mempool_segment_manager_memory_block.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/memory/port_pool_memory_block.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/generic_memory_block.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_block.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/memory_provider.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp, iceoryx_posh/source/roudi/memory/memory_block.cpp, iceoryx_posh/source/roudi/memory/memory_provider.cpp, iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp, iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp, iceoryx_posh/source/roudi/memory/port_pool_memory_block.cpp, iceoryx_posh/test/mocks/roudi_memory_block_mock.hpp, iceoryx_posh/test/moduletests/test_roudi_generic_memory_block.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
=> Iox #842 cleanup memory provider and memory block

CHANGELOG.md, iceoryx_hoofs/platform/mac/source/socket.cpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
=> iox-#903 timed{send,receive} supported in mac os

iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp, iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp
=> iox-#282 Fix deprecated-copy warning

README.md, doc/website/getting-started/examples/icedocker.md, iceoryx_examples/README.md, iceoryx_examples/icedelivery_in_c/README.md, iceoryx_examples/icedocker/README.md, iceoryx_examples/icedocker/docker-compose.yml, tools/iceoryx_build_test.sh
=> iox-#924 Add icedocker example readme

CHANGELOG.md, iceoryx_binding_c/CMakeLists.txt, iceoryx_binding_c/include/iceoryx_binding_c/config.h, iceoryx_binding_c/source/c_config.cpp, iceoryx_binding_c/test/moduletests/test_config.cpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp
=> Iox #930 add c binding for posh settings

CHANGELOG.md, QUALITY_DECLARATION.md, README.md
=> Iox #910 quality declaration document

.github/workflows/build-test.yml, CHANGELOG.md, iceoryx_binding_c/source/c_wait_set.cpp, iceoryx_binding_c/test/moduletests/test_notification_info.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_binding_c/test/moduletests/test_user_trigger.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, tools/ci/build-test-ubuntu-with-sanitizers.sh, tools/ci/build-test-ubuntu.sh, tools/ci/build-ubuntu-with-latest-clang-gcc.sh
=> Iox #932 handle nullptr callbacks in waitset

CHANGELOG.md, iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
1. [X] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Update the PR title
1. [X] Relevant issues are linked
1. [X] Add sensible notes for the reviewer
1. [X] All checks have passed (except `task-list-completed`)
1. [X] Assign PR to reviewer …
=> iox-#961 Use Multi-Arch compliant install destinations

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
=> Make `string::capacity()` static

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/optional.inl, iceoryx_hoofs/test/moduletests/test_cxx_optional.cpp
Signed-off-by: Marika Lehmann <marika.lehmann@apex.ai> …
=> iox-#967 Extend ctor for in place construction

CHANGELOG.md, CONTRIBUTING.md, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/source/capro/service_description.cpp, iceoryx_posh/source/popo/client_options.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> iox-#415 Rename variable and test case name in `ServiceRegistry_test` and fix bug in `ServiceDescription` c'tor

CHANGELOG.md, iceoryx_posh/CMakeLists.txt, iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp, iceoryx_posh/source/popo/publisher_options.cpp, iceoryx_posh/source/popo/subscriber_options.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_options.cpp, iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp
=> Iox #989 handle deserialization errors for publisher and subscriber options

CHANGELOG.md, iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_id.hpp, iceoryx_hoofs/source/cxx/unique_id.cpp, iceoryx_hoofs/test/moduletests/test_cxx_unique_id.cpp
=> Iox #1010 unique id class

CHANGELOG.md, iceoryx_binding_c/include/iceoryx_binding_c/enums.h, iceoryx_binding_c/source/cpp2c_enum_translation.cpp, iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_notification_info.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/memory_manager.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/source/mepoo/memory_manager.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_mepoo_shm_safe_unmanaged_chunk.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp, iceoryx_posh/test/moduletests/test_popo_client_port.cpp, iceoryx_posh/test/moduletests/test_popo_used_chunk_list.cpp
=> Iox #954 use cxx::expected for MemoryManager::getChunk

iceoryx_binding_c/test/moduletests/test_c2cpp_enum_translation.cpp, iceoryx_binding_c/test/moduletests/test_chunk.cpp, iceoryx_binding_c/test/moduletests/test_config.cpp, iceoryx_binding_c/test/moduletests/test_cpp2c_enum_translation.cpp, iceoryx_binding_c/test/moduletests/test_cpp2c_service_description_translation.cpp, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_log.cpp, iceoryx_binding_c/test/moduletests/test_node.cpp, iceoryx_binding_c/test/moduletests/test_notification_info.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_runtime.cpp, iceoryx_binding_c/test/moduletests/test_service_description.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_binding_c/test/moduletests/test_types.cpp, iceoryx_binding_c/test/moduletests/test_user_trigger.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, tools/ci/build-ubuntu-with-latest-clang-gcc.sh
=> Add unique test id's to C binding tests

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/mman.hpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp
=> Iox #1036 in place creation for memory map

CHANGELOG.md, iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h, iceoryx_binding_c/source/c_subscriber.cpp, iceoryx_examples/iceoptions/README.md, iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/pub_sub_port_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_roudi.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_roudi.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp, iceoryx_posh/source/popo/ports/publisher_port_data.cpp, iceoryx_posh/source/popo/ports/publisher_port_roudi.cpp, iceoryx_posh/source/popo/ports/subscriber_port_data.cpp, iceoryx_posh/source/popo/ports/subscriber_port_multi_producer.cpp, iceoryx_posh/source/popo/ports/subscriber_port_roudi.cpp, iceoryx_posh/source/popo/ports/subscriber_port_single_producer.cpp, iceoryx_posh/source/popo/subscriber_options.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp, iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp, iceoryx_posh/test/moduletests/test_roudi_portpool.cpp
=> Iox #1029 implement strict history capacity matching

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/capro/service_description.cpp, iceoryx_posh/source/popo/ports/interface_port_data.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_base_port.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> Iox #415 remove InvalidIdString and isValid() from ServiceDescription

CHANGELOG.md, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> Iox #415 add event parameter to find service

CHANGELOG.md, iceoryx_hoofs/test/moduletests/test_posix_signal_watcher.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp
=> iox-#1062 Implement stream operator for ChunkReceiveResult and AllocationError

doc/aspice_swe3_4/example/iceoryx_component/test/moduletests/test_example_base_class.cpp, iceoryx_dds/test/moduletests/test_cyclone_data_reader.cpp, iceoryx_dds/test/moduletests/test_dds_to_iox.cpp, iceoryx_dds/test/moduletests/test_iox_to_dds.cpp
=> iox-#988 Add unique test identifiers to ASPICE example and Cylcone DDS gateway

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_pipe.hpp, iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp, iceoryx_hoofs/test/moduletests/test_cxx_filesystem.cpp, iceoryx_hoofs/test/moduletests/test_shared_memory.cpp, iceoryx_hoofs/test/moduletests/test_shared_memory_object.cpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl, iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
=> Iox #1036 in place creation for shared memory

iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> Iox #415 refactor service registry

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
=> iox-#1076 replace result_of with invoke_result

iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
=> iox-#1108 Fix potential segfault in string

CHANGELOG.md, iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl, iceoryx_dds/test/moduletests/test_iox_to_dds.cpp, iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp, iceoryx_posh/source/capro/capro_message.cpp, iceoryx_posh/source/popo/ports/publisher_port_roudi.cpp, iceoryx_posh/source/popo/ports/server_port_roudi.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/moduletests/test_capro_message.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp, iceoryx_posh/test/moduletests/test_popo_server_port_roudi.cpp
=> iox-#27 Refactor CaproMessageSubType to be able to use ServerPorts with InterfacePorts [stacked PR #1.5]

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_examples/iceperf/base.cpp, iceoryx_hoofs/source/log/logstream.cpp, iceoryx_posh/source/runtime/ipc_runtime_interface.cpp
=> Iox #1130 replace high resolution clock with system clock and steady clock

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.inl, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
=> iox-#938 check for publisher destruction in does violate communication policy

iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/typed_port_api_trait.hpp, iceoryx_posh/include/iceoryx_posh/popo/client.hpp, iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/server.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
=> Iox #27 add typed client and server api [stacked PR #5]

iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> Iox #1150 remove findservice with container from discovery

iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.hpp, iceoryx_posh/test/mocks/client_mock.hpp, iceoryx_posh/test/mocks/server_mock.hpp, iceoryx_posh/test/moduletests/test_base_port.cpp, iceoryx_posh/test/moduletests/test_popo_base_client.cpp, iceoryx_posh/test/moduletests/test_popo_base_server.cpp, iceoryx_posh/test/moduletests/test_popo_client.cpp, iceoryx_posh/test/moduletests/test_popo_server.cpp, iceoryx_posh/test/moduletests/test_popo_untyped_client.cpp, iceoryx_posh/test/moduletests/test_popo_untyped_server.cpp
=> iox-#27 Add tests for typed client [stacked PR #5.1]

.clang-tidy, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp, iceoryx_posh/source/roudi/roudi_cmd_line_parser_config_file_option.cpp
=> Iox #299 fix clang tidy warnings

iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/integrationtests/test_client_server.cpp, iceoryx_posh/test/moduletests/test_popo_client_port.cpp, iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager_client_server.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp
This PR adds integration tests for client and server and fixed an issue found with the tests. …
=> iox-#27 integration tests

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp
=> iox-#1192 clamp history request

iceoryx_examples/icedocker/README.md
=> iox-#743 review docker example

iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp
=> iox-#1218 Remove potential dangerous usage of storage in binding C tests

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_binding_c/CMakeLists.txt, iceoryx_hoofs/CMakeLists.txt, iceoryx_posh/CMakeLists.txt
Adds a CMake option `APPEND_PROJECT_NAME_TO_INCLUDEDIR` defaulting to `ON`
that appends ${PROJECT_NAME} to the directory headers are installed. This is to support ros2/ros2#1150.
Pretty similar to https://github.com/eclipse-cyclonedds/cyclonedds/pull/1169
Relevant issue: https://github.com/eclipse-iceoryx/iceoryx/issues/1194
When using ROS 2 and Colcon it's possible to have two versions of a package installed: typically one from the debian packages (like `ros-[rosdistro]-iceoryx-binding-c`) and another in a from-source workspace. In Colcon terms this is called "overriding a package", and the `/opt/ros/[rosdistro]` folder would be called the underlay while the from-source workspace would be called the overlay. A user would do this when they want to try a newer version of a package without …
=> iox-#1194 Install includes to include/${PROJECT_NAME}

iceoryx_examples/iceoptions/README.md, iceoryx_examples/iceoptions/iox_publisher_with_options.cpp, iceoryx_examples/iceoptions/iox_subscriber_with_options.cpp
=> iox-#743 Validation of iceoption example

iceoryx_examples/iceperf/CMakeLists.txt, iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp
=> iox-#1243 convert unix domain socket tests to timing tests

iceoryx_binding_c/include/iceoryx_binding_c/config.h
Declaring a function in C that takes no argument requires "(void)".
With strict warning settings, C compilers will issue a warning.
Fixes #1280
Signed-off-by: Erik Boasson <eb@ilities.com> …
=> iox-#1280 use proper prototypes in C binding

QUALITY_DECLARATION.md, iceoryx_examples/complexdata/README.md, iceoryx_examples/iceoptions/README.md, iceoryx_examples/request_response/README.md
[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-message …
=> iox-#743 Set documentation links to `latest`/`master`

iceoryx_examples/waitset_in_c/README.md, iceoryx_examples/waitset_in_c/ice_c_waitset_timer_driven_execution.c
=> Iox #743 fix windows c waitset example

doc/website/.pages, doc/website/getting-started/overview.md, doc/website/release-notes/.pages, doc/website/release-notes/iceoryx-v2-0-0.md
=> iox-#743 Fixes to make docs exportable (`v2.x`)

doc/design/error-handling.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/hoofs_logging.hpp, iceoryx_hoofs/source/log/hoofs_logging.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_integrationtest/iceoryx_integrationtest/test_roudi_startup_shutdown.py
=> iox-#971 Remove success output in shared memory object

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
=> Iox #208 add clear method to string

iceoryx_examples/icediscovery/CMakeLists.txt, iceoryx_examples/icediscovery/README.md, iceoryx_examples/icediscovery/include/discovery_blocking.hpp, iceoryx_examples/icediscovery/iox_find_service.cpp, iceoryx_examples/icediscovery/iox_offer_service.cpp, iceoryx_examples/icediscovery_in_c/README.md, iceoryx_examples/icediscovery_in_c/iox_c_find_service.c, iceoryx_examples/icediscovery_in_c/iox_c_offer_service.c, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_in_c_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_monitoring.py
=> iox-#1295 Rework `icediscovery` example

doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
1. ~~[ ] Changelog updated [in the unreleased section][changelog] including API breaking changes~~ …
=> iox-#1362 Clarify documentation of optionals

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dds/CMakeLists.txt
The custom_command for generating the Mempool header
was not explicitly declared as dep to iceoryx_dds
but was still working because it was always executed
before building iceworyx_dds when using CMake on multiple cores
1. …
=> iox-#1364 Add dep for idlc command to iceoryx_dds

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/semaphore_interface.hpp, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/unnamed_semaphore.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/semaphore.hpp, iceoryx_hoofs/source/posix_wrapper/semaphore_interface.cpp, iceoryx_hoofs/source/posix_wrapper/unnamed_semaphore.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_and_then.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_or_else.cpp, iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp, iceoryx_hoofs/test/moduletests/test_posix_unnamed_semaphore.cpp
=> iox-#751 create unnamed semaphore

iceoryx_dds/CMakeLists.txt, iceoryx_posh/CMakeLists.txt
=> iox-#1287 Fix CMake install paths

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.inl
=> iox-#1396 Fix data race in concurrent::FIFO push

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_runtime_interface.hpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/runtime/ipc_runtime_interface.cpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
=> iox-#1436 disable heartbeats in apps when not monitoring

CONTRIBUTING.md
=> iox-#1394 Mention Axivion syntax in `CONTRIBUTING.md`

README.md, doc/website/FAQ.md, doc/website/getting-started/overview.md
> Left-over from shortly after the Blueberry release …
=> iox-#1295 Extend FAQ with more questions

iceoryx_binding_c/test/CMakeLists.txt, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, iceoryx_binding_c/test/test.hpp, iceoryx_posh/testing/include/iceoryx_posh/testing/mocks/posh_runtime_mock.hpp
=> iox-#1196 Fix compiler warnings in binding c tests

.clang-tidy, .github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/test/.clang-tidy, iceoryx_dds/test/.clang-tidy, iceoryx_hoofs/include/iceoryx_hoofs/cxx/.clang-tidy, iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_hoofs/source/units/duration.cpp, iceoryx_hoofs/test/.clang-tidy, iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp, iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp, iceoryx_hoofs/test/moduletests/test_cxx_deadline_timer.cpp, iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp, iceoryx_hoofs/test/moduletests/test_unit_duration.cpp, iceoryx_posh/test/.clang-tidy
=> Iox #1196 fix clang tidy warnings integration branch

iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl, iceoryx_hoofs/test/.clang-tidy, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_and_then.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_common.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_concat_multiple_calls.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_expect.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_or_else.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_types.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_value_or.cpp
=> Iox #1196 fix functional interface warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
=> Iox #1196 fix stack warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/serialization.inl, iceoryx_hoofs/test/moduletests/test_cxx_serialization.cpp
=> Iox #1196 fix serialization warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/poor_mans_heap.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/poor_mans_heap.inl, iceoryx_hoofs/test/moduletests/test_cxx_poor_mans_heap.cpp
=> iox-#1196 Add lint suppressions and fix warnings for PoorMansHeap

iceoryx_hoofs/include/iceoryx_hoofs/cxx/list.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/list.inl, iceoryx_hoofs/test/moduletests/test_cxx_list.cpp
=> Iox #1196 fix list warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl, iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp
=> iox-#1196 Fix clang tidy warnings in `cxx::unique_ptr`

.clang-tidy, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.inl, iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp
=> iox-#1196 fix periodic task warnings

iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.inl, iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
=> iox-#1196 fix smart lock warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.inl, iceoryx_hoofs/source/concurrent/loffli.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp
=> iox-#1196 fix loffli warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp, iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
=> iox-#1196 Fix clang tidy warnings in `cxx::variant`

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl, iceoryx_hoofs/test/moduletests/test_cxx_function.cpp
=> iox-#1196 Fix clang-tidy warning in storable_function

.github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/source/posix_wrapper/file_lock.cpp
=> Iox #1440 fix file lock leak in release 2.0

iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_semaphore.hpp, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/unnamed_semaphore.hpp, iceoryx_hoofs/source/posix_wrapper/named_semaphore.cpp, iceoryx_hoofs/source/posix_wrapper/unnamed_semaphore.cpp, iceoryx_hoofs/test/moduletests/test_posix_semaphore_common.hpp, iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp
=> iox-#1196 fix warnings in semaphore

iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/named_pipe.hpp, iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp
=> iox-#1196 fix warnings in named pipe

iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp, iceoryx_hoofs/source/posix_wrapper/file_lock.cpp, iceoryx_hoofs/test/moduletests/test_posix_file_lock.cpp
=> iox-#1196 Fix warnings in file lock

iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/message_queue.hpp, iceoryx_hoofs/source/posix_wrapper/message_queue.cpp, iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp
=> iox-#1196 fix warnings in message queue and ipc channel test

iceoryx_hoofs/source/posix_wrapper/mutex.cpp, iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp
=> iox-#1196 fix warnings in mutex

iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl, iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp
=> iox-#1394 iox-#1196 Address Axivion and clang-tidy findings for `cxx::function_ref`

iceoryx_hoofs/source/posix_wrapper/types.cpp, iceoryx_hoofs/test/moduletests/test_posix_types.cpp
=> iox-#1196 Fix warnings in types

iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/posix_call.inl, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/platform_correction.hpp, iceoryx_hoofs/test/moduletests/test_posix_posix_call.cpp
=> iox-#1196 fix warnings in posix call

iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/poor_mans_heap.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp, iceoryx_hoofs/test/moduletests/test_cxx_forward_list.cpp, iceoryx_hoofs/test/moduletests/test_cxx_function_ref.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_expect.cpp, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp, iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp, iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp, iceoryx_hoofs/test/moduletests/test_file_reader.cpp, tools/scripts/clang_tidy_check.sh
=> iox-#1196 Fix left-over clang-tidy warnings in `cxx::vector` and remove space in suppressions

.clang-tidy, .clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/allocator.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/allocator.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/shared_memory.cpp, iceoryx_hoofs/test/moduletests/test_allocator.cpp, iceoryx_hoofs/test/moduletests/test_shared_memory.cpp, iceoryx_hoofs/test/moduletests/test_shared_memory_object.cpp
=> Iox #1196 fix clang tidy warnings shared memory object

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/sofi.inl, iceoryx_hoofs/test/moduletests/test_concurrent_sofi.cpp, iceoryx_hoofs/test/stresstests/test_stress_sofi.cpp
=> iox-#1196 fix sofi warnings

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.inl, iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp
=> iox-#1196 Fix clang tidy warnings in `RelativePointerData`

.github/workflows/build-test.yml, tools/ci/build-test-ubuntu-bazel.sh
=> iox-#1547 Remove GitHub Caching from Bazel build in CI

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl, iceoryx_hoofs/source/concurrent/loffli.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl, iceoryx_posh/source/mepoo/mem_pool.cpp, iceoryx_posh/source/mepoo/shared_chunk.cpp, iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
=> iox-#1196 Remove conversion operator in `RelativePointer`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp, iceoryx_hoofs/source/posix_wrapper/posix_access_rights.cpp
=> Iox 1556 remove posix rights struct

iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer_data.inl, iceoryx_hoofs/source/relocatable_pointer/relative_pointer_data.cpp, iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
=> iox-#1394 Address AUTOSAR warnings in `RelativePointerData`

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp, iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/creation.hpp
=> iox-#1196 activate clang-tidy check on design_pattern

.clang-tidy-diff-scans.txt, iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.hpp, iceoryx_dust/include/iceoryx_dust/relocatable_pointer/relocatable_ptr.inl, iceoryx_dust/test/moduletests/test_relocatable_ptr.cpp
=> iox-#1196 Fix clang-tidy warnings in relocatable ptr

iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl, iceoryx_hoofs/source/posix_wrapper/shared_memory_object/memory_map.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_receiver.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl
=> iox-#1566 Replace QAC++ suppressions with Axivion AUTOSAR suppressions

iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp
=> iox-#1394 Fix Axivion warnings for builder.hpp

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
Setting the SOVERSION to a major project version
will prevent that libraries from different
major releases will try link against each other …
=> iox-#1308 Set SOVERSION for shared libraries

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp, iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp, iceoryx_posh/source/roudi/roudi_cmd_line_parser.cpp, iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
1. [x] ~~All touched (C/C++) source code files are added to `./clang-tidy-diff-scans.txt`~~ not done for posh …
=> iox-#1580 Disable monitoring feature in RouDi by default

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/roudi/port_manager.cpp
1. [x] ~~All touched (C/C++) source code files are added to `./clang-tidy-diff-scans.txt`~~ not done for posh …
=> iox-#1575 Properly initialize `ServiceRegistry` in shared memory

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl, iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/smart_chunk.inl, iceoryx_posh/test/moduletests/test_popo_request.cpp, iceoryx_posh/test/moduletests/test_popo_response.cpp, iceoryx_posh/test/moduletests/test_popo_sample.cpp, iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp
=> iox-#1571 Add check for `nullptr` in `unique_ptr::get()`

.github/PULL_REQUEST_TEMPLATE.md
=> iox-#1196 Restrict clang tidy diff scan to iceoryx_hoofs in PR template

iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp, iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/mac/source/pthread.cpp, iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/unix/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/source/posix_wrapper/thread.cpp
=> iox-#1365 set thread name in start routine

iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/types.hpp, iceoryx_hoofs/platform/linux/include/iceoryx_hoofs/platform/platform_settings.hpp, iceoryx_hoofs/platform/mac/include/iceoryx_hoofs/platform/platform_settings.hpp, iceoryx_hoofs/platform/qnx/include/iceoryx_hoofs/platform/platform_settings.hpp, iceoryx_hoofs/platform/unix/include/iceoryx_hoofs/platform/platform_settings.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/platform_settings.hpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
=> iox-#1394 fix axivion violation for type traits hpp types hpp

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/algorithm.inl, iceoryx_hoofs/test/moduletests/test_cxx_algorithm.cpp, iceoryx_posh/source/mepoo/chunk_settings.cpp, iceoryx_posh/source/roudi/memory/mempool_collection_memory_block.cpp, iceoryx_posh/source/roudi/memory/mempool_segment_manager_memory_block.cpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_settings.cpp
=> iox-1394 fix AUTOSAR violations in algorithm files

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl
=> iox-#1596 Add check for `nullptr` in `RelativePointer`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/popo/building_blocks/locking_policy.cpp
=> iox-#1609 Add log message before terminating

iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
=> iox-1394 fix AUTOSAR and CERT violations in stack

iceoryx_binding_c/test/moduletests/main.cpp, iceoryx_dust/test/moduletests/test_dust_modules.cpp, iceoryx_hoofs/test/integrationtests/test_hoofs_integration.cpp, iceoryx_hoofs/test/moduletests/test_hoofs_modules.cpp, iceoryx_hoofs/testing/CMakeLists.txt, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp, iceoryx_hoofs/testing/logger.cpp, iceoryx_posh/test/integrationtests/test_posh_integration.cpp, iceoryx_posh/test/moduletests/test_posh_modules.cpp
=> Iox-#1345 Add testing logger [Stacked PR 2]

iceoryx_dust/test/moduletests/test_relocatable_ptr.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_index_queue.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue_buffer.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue_cyclic_index.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_loffli.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_resizeable_lockfree_queue.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_types.hpp, iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp, iceoryx_hoofs/test/moduletests/test_logstream.cpp, iceoryx_hoofs/test/moduletests/test_posix_semaphore_interface.cpp, iceoryx_hoofs/test/moduletests/test_posix_signal_handler.cpp, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp, iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp, iceoryx_hoofs/test/stresstests/test_resizeable_lockfree_queue_stresstest.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_base_port.cpp, iceoryx_posh/test/moduletests/test_popo_base_client.cpp, iceoryx_posh/test/moduletests/test_popo_base_server.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp, iceoryx_posh/test/moduletests/test_popo_smart_chunk.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> iox-#1653 Remove Wgnu-zero-variadic-macro-arguments suppression from TYPED_TEST_SUITE

iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-1643 Revert destruction order in copy and move assignment operators of cxx::vector

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-1662 change vector::erase return type to bool

iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/source/cxx/requires.cpp
=> iox-#1673 Improve usability of cxx::Expects and cxx::Ensures

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
=> iox-#1668 Set chunk header originId always

iceoryx_hoofs/test/moduletests/test_posix_mutex.cpp, iceoryx_posh/include/iceoryx_posh/popo/trigger_handle.hpp, iceoryx_posh/source/popo/trigger_handle.cpp
=> iox-#1683 Disable robust mutex test for qnx

iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/assignment.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/comparable.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/constructor.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/convertable.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/internal.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/protected_constructor.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/sortable.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl
=> iox-1394 fix AUTOSAR violations in newtype

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl, iceoryx_hoofs/test/moduletests/test_cxx_unique_ptr.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/client_impl.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/server_impl.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber_impl.inl
=> iox-1655 Remove `reset` method from `cxx::unique_ptr`

iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/loffli.hpp, iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/chunk_management.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp, iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp, iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp, iceoryx_posh/source/mepoo/shared_chunk.cpp, iceoryx_posh/source/roudi/memory/memory_provider.cpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
=> iox-#605 Move `RelativePointer` from internal to public include directory

iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp
=> iox-1394 fix axivion violation for attributes hpp

.clang-format, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/console_logger.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logformat.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/building_blocks/logger.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl, iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/console_logger.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logformat.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/building_blocks/logger.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp, iceoryx_hoofs/source/log/building_blocks/console_logger.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_hoofs/test/moduletests/test_logstream.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp
=> iox-#1345 fix axivion warnings in logger files

iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/test_definitions.hpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment_management.cpp
=> iox-#1635 Use GTEST_SKIP for test which require additional user

iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl, iceoryx_hoofs/source/cxx/functional_interface.cpp
=> iox-1394 fix axivion warnings for functional interface

.github/actions/install-iceoryx-deps-and-clang/action.yml, .github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/gateway/channel.inl, iceoryx_posh/include/iceoryx_posh/popo/enum_trigger_type.hpp
=> iox-#1736 use clang format 15 in ci

iceoryx_hoofs/cmake/IceoryxHoofsDeployment.cmake, iceoryx_hoofs/include/iceoryx_hoofs/internal/log/logstream.inl, iceoryx_hoofs/include/iceoryx_hoofs/log/logging.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor_data.inl
=> iox-#1345 do not create logstream object when logging is off

.github/PULL_REQUEST_TEMPLATE.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-1394 fix AUTOSAR violations in vector

iceoryx_hoofs/include/iceoryx_hoofs/cxx/function_ref.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/function_ref.inl, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp
=> iox-#1394 Address left-over AUTOSAR findings in `function_ref`

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/storable_function.inl
=> Iox 1394 fix axivion violations in cxx function

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl, iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp
=> iox-1750 Add `Expects` to `cxx::expected::value()` and `get_error()`

.github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/CMakeLists.txt, iceoryx_posh/testing/CMakeLists.txt
Signed-off-by: Dietrich Kroenke <dietrich.kroenke@apex.ai>
1. [x] …
=> iox-#1516 Refactor iceoryx_posh testing lib into own CMake file

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl, iceoryx_hoofs/memory/include/iox/unique_ptr.hpp, iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp, iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
=> iox-1751 Add equality operators for `expected` and `variant`

iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/unique_ptr.hpp
=> iox-#1391 Fix legacy build when using `unique_ptr`

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/relative_pointer_data.hpp, iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl
=> iox-#1394 Address re-introduced AUTOSAR warnings

QUALITY_DECLARATION.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp, iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
=> iox-1394 fix autosar violations in variant

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp
=> iox-1394 fix AUTOSAR violations in variant_internal

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-#1823 Fix double move in emplace

iceoryx_hoofs/source/posix_wrapper/mutex.cpp
=> iox-#1835 fixed spelling error in mutex log error msg

iceoryx_hoofs/source/posix_wrapper/mutex.cpp
=> iox-#1835 updated mutex log error message

iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/functional_interface.inl
=> iox-1394 Fix AUTOSAR violations in functional_interface

.github/workflows/lint_master.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/include/iceoryx_dust/design/creation.hpp, iceoryx_dust/include/iceoryx_dust/internal/design/creation.inl, iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp, iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp, iceoryx_examples/iceperf/mq.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_pointer.hpp
=> iox-#1036 move creation pattern to dust

iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl, iceoryx_hoofs/source/units/duration.cpp, iceoryx_hoofs/test/moduletests/test_unit_duration.cpp
=> iox-#1394 Fix axivion warnings in duration class

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl, iceoryx_posh/test/moduletests/test_popo_waitset.cpp
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~ …
=> iox-1855 Return in `WaitSet::wait` if data was send before `WaitSet::attachState`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp, iceoryx_dust/include/iceoryx_dust/internal/cli/option_manager.inl, iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl, iceoryx_dust/source/posix_wrapper/named_pipe.cpp, iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp, iceoryx_dust/test/moduletests/test_cxx_string_conversion.cpp, iceoryx_hoofs/utility/include/iox/detail/into.inl, iceoryx_hoofs/utility/include/iox/into.hpp, iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/test/moduletests/test_gw_gateway_generic.cpp, iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager_fixture.hpp, iceoryx_posh/test/moduletests/test_roudi_portpool.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> iox-1612 make lossy std string conversion more visible

iceoryx_hoofs/container/include/iox/uninitialized_array.hpp, iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp
Signed-off-by: Jeff Ithier <jeff.ithier@apex.ai>
1. [ ] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [x] Assign PR …
=> iox-#1892 Ensure the NonZeroedBuffer does not zero its elements

iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp, iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl, iceoryx_hoofs/design/include/iox/detail/functional_interface.inl, iceoryx_hoofs/include/iceoryx_hoofs/cxx/algorithm.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp, iceoryx_hoofs/include/iceoryx_hoofs/memory/relative_pointer.inl, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp, iceoryx_hoofs/memory/include/iox/bump_allocator.hpp, iceoryx_hoofs/memory/include/iox/memory.hpp, iceoryx_hoofs/memory/source/bump_allocator.cpp, iceoryx_hoofs/primitives/include/iox/size.hpp, iceoryx_hoofs/test/moduletests/test_time_unit_duration.cpp, iceoryx_hoofs/test/moduletests/test_utility_into.cpp, iceoryx_hoofs/time/include/iox/detail/duration.inl, iceoryx_hoofs/time/include/iox/duration.hpp, iceoryx_hoofs/time/source/duration.cpp, iceoryx_hoofs/utility/include/iox/detail/into.inl, iceoryx_hoofs/utility/include/iox/into.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/server_port_user.inl
=> iox-1394 fix axivion warnings for multiple files

.github/workflows/build-test.yml, CONTRIBUTING.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_integrationtest/CMakeLists.txt, iceoryx_integrationtest/Readme.md, iceoryx_integrationtest/package.xml, tools/ci/run-integration-test.sh
=> Iox 1960 update integrationtests

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/buffer/include/iox/detail/stack.inl, iceoryx_hoofs/buffer/include/iox/stack.hpp, iceoryx_hoofs/test/moduletests/test_buffer_stack.cpp
=> iox-1893 fix memory leak in stack

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_platform/linux/include/iceoryx_platform/platform_settings.hpp, iceoryx_platform/mac/include/iceoryx_platform/platform_settings.hpp, iceoryx_platform/qnx/include/iceoryx_platform/platform_settings.hpp, iceoryx_platform/unix/include/iceoryx_platform/platform_settings.hpp, iceoryx_platform/win/include/iceoryx_platform/platform_settings.hpp
1. ~~[ ] Tests follow the [best practice for testing][testing]~~ …
=> iox-#1934 Alias invoke_result to correct implementation based on C++ version

iceoryx_examples/iceperf/uds.cpp, iceoryx_platform/linux/include/iceoryx_platform/fcntl.hpp, iceoryx_platform/linux/source/fnctl.cpp, iceoryx_platform/mac/include/iceoryx_platform/fcntl.hpp, iceoryx_platform/mac/source/fnctl.cpp, iceoryx_platform/qnx/include/iceoryx_platform/fcntl.hpp, iceoryx_platform/qnx/source/fnctl.cpp, iceoryx_platform/unix/include/iceoryx_platform/fcntl.hpp, iceoryx_platform/unix/source/fnctl.cpp, iceoryx_platform/win/include/iceoryx_platform/fcntl.hpp, iceoryx_platform/win/source/fnctl.cpp
=> iox-1955 use posix compliant calls to set nonblocking flags

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/popo/publisher_impl.inl
=> iox-#1963 Fix UB in publishCopyOf and publishResultOf

iceoryx_hoofs/testing/testing_logger.cpp
=> iox-#1755 flush testing logger on terminate

iceoryx_hoofs/test/moduletests/test_vocabulary_expected.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/expected.inl, iceoryx_hoofs/vocabulary/include/iox/expected.hpp
=> iox-#1969 rework constructors for expected

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/source/c_chunk.cpp, iceoryx_binding_c/source/c_listener.cpp, iceoryx_binding_c/source/c_node.cpp, iceoryx_binding_c/source/c_notification_info.cpp, iceoryx_binding_c/source/c_publisher.cpp, iceoryx_binding_c/source/c_server.cpp, iceoryx_binding_c/source/c_subscriber.cpp, iceoryx_binding_c/source/c_user_trigger.cpp, iceoryx_binding_c/test/moduletests/test_chunk.cpp, iceoryx_binding_c/test/moduletests/test_client.cpp, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_node.cpp, iceoryx_binding_c/test/moduletests/test_notification_info.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_request_header.cpp, iceoryx_binding_c/test/moduletests/test_response_header.cpp, iceoryx_binding_c/test/moduletests/test_server.cpp, iceoryx_binding_c/test/moduletests/test_service_discovery.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_binding_c/test/moduletests/test_user_trigger.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp
=> Check for nullptr in c bindings

.github/workflows/lint_pull_request.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_examples/singleprocess/README.md, iceoryx_examples/singleprocess/single_process.cpp, iceoryx_posh/include/iceoryx_posh/roudi/cmd_line_args.hpp, iceoryx_posh/include/iceoryx_posh/roudi/roudi_cmd_line_parser.hpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/test/moduletests/test_roudi_iceoryx_roudi_app.cpp
=> iox-#1994 Use logger for 'RouDi is ready for clients' message

.bazelrc, .github/actions/install-iceoryx-deps-and-clang/action.yml, .github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, tools/ci/build-test-ubuntu-bazel.sh
=> iox-#1998 enable bazel build with clang

.bazelrc, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/test/BUILD.bazel
=> Additional bazel support sanitizer 

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp, iceoryx_dust/source/posix_wrapper/named_pipe.cpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
=> iox-#1036 builder pattern for named pipe

.clang-tidy-diff-scans.txt, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp, iceoryx_dust/include/iceoryx_dust/posix_wrapper/named_pipe.hpp, iceoryx_dust/source/posix_wrapper/message_queue.cpp, iceoryx_dust/source/posix_wrapper/named_pipe.cpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/unix_domain_socket.hpp, iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp, iceoryx_hoofs/test/moduletests/test_unix_domain_sockets.cpp, iceoryx_posh/source/runtime/ipc_interface_base.cpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp
=> iox-#1036 builder pattern for unix domain socket

doc/design/error-handling.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/mepoo/mem_pool.cpp, iceoryx_posh/test/integrationtests/test_shm_sigbus_handler.cpp, iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp, iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp
=> iox-#1613 Remove EXPECT_DEATH

iceoryx_hoofs/reporting/include/iox/detail/log/building_blocks/logformat.inl, iceoryx_hoofs/reporting/include/iox/detail/log/logstream.inl, iceoryx_hoofs/reporting/include/iox/log/building_blocks/logformat.hpp, iceoryx_hoofs/reporting/include/iox/log/logstream.hpp, iceoryx_hoofs/test/moduletests/test_reporting_logstream.cpp
=> iox-#1755 Distinct overloads for arithmetic types for logstream

.github/workflows/lint_pull_request.yml, doc/design/logging.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/error_reporting/custom/default/error_reporting.inl, iceoryx_hoofs/include/iceoryx_hoofs/error_reporting/error_logging.hpp, iceoryx_hoofs/reporting/include/iox/detail/log/logstream.inl, iceoryx_hoofs/reporting/include/iox/log/logstream.hpp, iceoryx_hoofs/reporting/include/iox/logging.hpp, iceoryx_hoofs/test/moduletests/test_reporting_logging.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, tools/scripts/clang_tidy_check.sh
=> iox-#1755 Reintroduce lazy evaluation for the logging

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/test/moduletests/test_cxx_forward_list.cpp, iceoryx_hoofs/test/moduletests/test_container_vector.cpp, iceoryx_hoofs/test/moduletests/test_cxx_list.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/ctor_and_assignment_operator_test_class.hpp
=> iox-#2041 Move test class for ctor and assignment operator to hoofs testing

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/reporting/include/iox/detail/log/building_blocks/console_logger.inl, iceoryx_hoofs/reporting/include/iox/detail/log/logstream.inl, iceoryx_hoofs/reporting/include/iox/log/building_blocks/console_logger.hpp, iceoryx_hoofs/reporting/include/iox/log/logstream.hpp, iceoryx_hoofs/reporting/source/log/building_blocks/console_logger.cpp, iceoryx_hoofs/test/moduletests/test_reporting_logstream.cpp, iceoryx_platform/win/include/iceoryx_platform/unistd.hpp
=> iox-#1755 Add log bin and log raw

iceoryx_dust/test/moduletests/test_container_fixed_position_container.cpp, iceoryx_dust/test/moduletests/test_cxx_forward_list.cpp, iceoryx_hoofs/test/moduletests/test_container_vector.cpp, iceoryx_hoofs/test/moduletests/test_cxx_list.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/lifetime_and_assignment_tracker.hpp
=> iox-#2041 Rename 'CTorAndAssignmentOperatorTestClass' to 'LifetimeAndAssignmentTracker'

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_platform/linux/include/iceoryx_platform/mqueue.hpp
As stated in the mq_open man page ([1]) the mqueue.h include needs additional sys/stat.h include for mode_t definition.
Fixes musl compile:
In file included from .../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:17:
.../build/iceoryx-custom/iceoryx_platform/linux/include/iceoryx_platform/mqueue.hpp:23:49: error: ‘mode_t’ has not been declared
23 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr);
|                                                 ^~~~~~
.../build/iceoryx-custom/iceoryx_platform/linux/source/mqueue.cpp:26:49: error: ‘mode_t’ has not been declared
26 | mqd_t iox_mq_open4(const char* name, int oflag, mode_t mode, struct mq_attr* attr)
|                                                 ^~~~~~
[1] …
=> iox-#2072 Include mqueue.h needs sys/stat.h for mode_t (fixes musl compile)

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/container/include/iox/detail/fixed_position_container.inl, iceoryx_dust/container/include/iox/detail/fixed_position_container_helper.hpp, iceoryx_dust/container/include/iox/fixed_position_container.hpp, iceoryx_dust/test/moduletests/test_container_fixed_position_container.cpp
=> iox-#2052 Implement move/copy constructor and assignment for `FixedPositionContainer` 

.cirrus.yaml, iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl, iceoryx_hoofs/test/moduletests/test_vocabulary_string.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/string.inl, iceoryx_hoofs/vocabulary/include/iox/detail/variant.inl, iceoryx_hoofs/vocabulary/include/iox/variant.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl, iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp
=> iox-#2047 Fix gcc 13 warnings

.bazelrc, .clang-tidy, CONTRIBUTING.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/test/moduletests/test_cli_command_line_common.hpp, iceoryx_hoofs/README.md, iceoryx_platform/linux/IceoryxPlatformSettings.cmake, iceoryx_platform/qnx/IceoryxPlatformSettings.cmake, iceoryx_posh/test/CMakeLists.txt, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp, tools/ci/build-test-windows.ps1
=> iox-#2066 Switch to C++17

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mem_pool.hpp, iceoryx_posh/source/mepoo/mem_pool.cpp, iceoryx_posh/test/moduletests/test_mepoo_mempool.cpp
=> iox-#2087 Fix allocation for mempools larger than 4gb

doc/website/release-notes/iceoryx-unreleased.md, tools/introspection/CMakeLists.txt, tools/introspection/package.xml
1. [x] ~~Add a second reviewer for complex new features or larger refactorings~~
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to …
=> Add introspection to ROS release for `master` branch

iceoryx_dust/container/include/iox/detail/fixed_position_container.inl, iceoryx_dust/container/include/iox/detail/fixed_position_container_helper.hpp, iceoryx_dust/container/include/iox/fixed_position_container.hpp
Refactor `FixedPositionContainer::copy_and_move_impl` by new struct `SpecialCreationHelper` and enum class `SpecialCreationOperations` with C++17 features.
1. [x] …
=> iox-#2052 Refactor copy_and_move_impl

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl, iceoryx_hoofs/filesystem/include/iox/filesystem.hpp, iceoryx_hoofs/posix/design/include/iox/detail/file_management_interface.inl, iceoryx_hoofs/test/moduletests/test_filesystem_filesystem.cpp
=> iox-#2108 Public API to create 'access_rights' from value

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp
…ting the Roudi daemon to create a subscriber.
1. [x] All touched (C/C++) source code files from …
=> iox-#2121 Fix history request is out of limit.

CONTRIBUTING.md, doc/design/move_and_copy_helper.md, iceoryx_dust/container/include/iox/detail/fixed_position_container.inl, iceoryx_dust/container/include/iox/fixed_position_container.hpp, iceoryx_hoofs/design/include/iox/detail/move_and_copy_helper.inl, iceoryx_hoofs/design/include/iox/move_and_copy_helper.hpp, iceoryx_hoofs/test/moduletests/test_design_move_and_copy_helper.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/lifetime_and_assignment_tracker.hpp
=> Move `move_and_copy_helper` to `iceoryx/design`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/container/include/iox/detail/vector.inl
Optimize the vector class by specializing it for plain old data (POD) types, thereby eliminating the need for explicit constructors, destructors, and copy operators in the vector operations.
1. [x] Add …
=> iox-#2082 faster vector on POD data

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/posix/design/include/iox/file_management_interface.hpp, iceoryx_hoofs/posix/design/source/file_management_interface.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/segment_manager.inl, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
=> iox-#2023 Fix bad file descriptor error

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl, iceoryx_posh/include/iceoryx_posh/popo/listener.hpp, iceoryx_posh/include/iceoryx_posh/popo/notification_attorney.hpp, iceoryx_posh/source/popo/listener.cpp
=> iox-#2137 Merge 'ListenerImpl' back to 'Listener'

doc/design/error_reporting.md, iceoryx_hoofs/reporting/include/iox/assertions.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/error_reporting_impl.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/error_kind.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/errors.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/macros.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/types.hpp, iceoryx_hoofs/test/moduletests/error_reporting/test_error_reporting_macros.cpp, iceoryx_hoofs/testing/error_reporting/testing_support.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/error_reporting/testing_support.hpp
=> iox-#1032 Refactor 'IOX_REQUIRE'

iceoryx_hoofs/test/moduletests/test_utility_convert.cpp
=> Add edge test cases for 'convert::from_string'

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/posix/ipc/include/iox/detail/unix_domain_socket.inl, iceoryx_hoofs/posix/ipc/include/iox/unix_domain_socket.hpp, iceoryx_hoofs/posix/ipc/source/unix_domain_socket.cpp, iceoryx_hoofs/test/moduletests/test_posix_ipc_unix_domain_sockets.cpp
By default, the UnixDomainSocket class relies on std::string objects to send and receive data, as defined by its interface. However, this approach can potentially lead to dynamic memory allocation when handling larger data payloads that exceed the stack space optimization (SSO) limit.
To address this issue, an alternative API has been introduced that enables data transmission and reception using iox::string. This approach allows for direct data manipulation within stack memory, effectively eliminating the need for dynamic memory allocation.
1. [x] Changelog updated [in the …
=> iox-eclipse-iceoryx#2040 support for iox::string in UnixDomainSocket

iceoryx_hoofs/test/moduletests/test_utility_convert.cpp, iceoryx_hoofs/utility/include/iox/detail/convert.inl
=> Fix 'covert::from_string' test on aarch64 platform

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/posix/ipc/include/iox/detail/message_queue.inl, iceoryx_hoofs/posix/ipc/include/iox/message_queue.hpp, iceoryx_hoofs/posix/ipc/source/message_queue.cpp
By default, the MessageQueue class relies on std::string objects to send and receive data, as defined by its interface. However, this approach can potentially lead to dynamic memory allocation when handling larger data payloads that exceed the stack space optimization (SSO) limit.
To address this issue, an alternative API has been introduced that enables data transmission and reception using iox::string. This approach allows for direct data manipulation within stack memory, effectively eliminating the need for dynamic memory allocation.
1. [x] Changelog updated [in the unreleased …
=> iox-eclipse-iceoryx#1963 support for iox::string in MessageQueue

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/posix/ipc/include/iox/detail/named_pipe.inl, iceoryx_hoofs/posix/ipc/include/iox/named_pipe.hpp, iceoryx_hoofs/posix/ipc/source/named_pipe.cpp
By default, the NamedPipe class relies on std::string objects to send and receive data, as defined by its interface. However, this approach can potentially lead to dynamic memory allocation when handling larger data payloads that exceed the stack space optimization (SSO) limit.
To address this issue, an alternative API has been introduced that enables data transmission and reception using iox::string. This approach allows for direct data manipulation within stack memory, effectively eliminating the need for dynamic memory allocation.
1. [x] Changelog updated [in the unreleased …
=> iox-#1693 support for iox::string in NamedPipe

iceoryx_hoofs/container/include/iox/detail/vector.inl
=> iox-#2082 Always initialize members in 'iox::vector(count)'

iceoryx_hoofs/reporting/include/iox/assertions.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/custom/default/error_reporting_impl.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/error_forwarding.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/macros.hpp, iceoryx_hoofs/test/moduletests/error_reporting/test_custom_error_reporting.cpp
=> iox-#1032 Add stringified condition to the error output

iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/primitives/include/iox/iceoryx_hoofs_types.hpp, iceoryx_hoofs/reporting/include/iox/detail/log/building_blocks/logger.inl, iceoryx_hoofs/reporting/include/iox/log/building_blocks/logger.hpp, iceoryx_hoofs/reporting/source/logging.cpp, iceoryx_hoofs/test/moduletests/test_reporting_logging.cpp, iceoryx_platform/generic/include/iceoryx_platform/logging.hpp, iceoryx_platform/generic/source/logging.cpp, iceoryx_platform/mac/source/semaphore.cpp, iceoryx_platform/test/moduletests/test_platform_logging.cpp, iceoryx_platform/win/source/fnctl.cpp, iceoryx_platform/win/source/getopt.cpp, iceoryx_platform/win/source/handle_translator.cpp, iceoryx_platform/win/source/mman.cpp, iceoryx_platform/win/source/pthread.cpp, iceoryx_platform/win/source/semaphore.cpp, iceoryx_platform/win/source/socket.cpp, iceoryx_platform/win/source/win32_errorHandling.cpp
=> iox-#1755 Redirect printing in the platform layer to the logger

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/test/moduletests/test_vocabulary_optional.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/optional.inl, tools/introspection/source/introspection_app.cpp
Fixes the forwarding reference type in `iox::optional::operator=` when performing a direct assignment of the underlying value such that assigning `const` values is supported.
1. [ ] ~Add a second reviewer for complex new features or larger refactorings~
1. [x] Add sensible notes …
=> iox-#2224 Fix const value assignment in optional

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/test/moduletests/test_vocabulary_span.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/span_iterator.hpp
This PR fixes an incorrect assert which prevented the creation of the end iterator of a span
Fixes https://github.com/eclipse-iceoryx/iceoryx/issues/2241
1. [x] Assign PR to …
=> iox-#2241 Fix span iterator constructor

README.md
=> iox-#2244 Add ekxide.io as vendor

doc/website/FAQ.md
=>  Add doc how to using iceoryx as 3rdparty dependency 

iceoryx_posh/cmake/cpptoml/0001-cpptoml-cmake-version.patch, iceoryx_posh/cmake/cpptoml/CMakeLists.txt
This PR add a patch to the CMakeLists.txt of cpptoml in order to prevent warnings with newer cmake versions. It is based on #2232 for the v2.0 branch.
1. [x] Assign PR to …
=> iox-#2011 Add patch to use cmake 3.16 for cpptoml

doc/aspice_swe3_4/swe_docu_guidelines.md, doc/website/release-notes/iceoryx-unreleased.md
This PR documents the workaround we used to include the documentation in internal headers which where referenced by a trampoline header. …
=> iox-#1293 Document workaround for documentation in internal headers

doc/aspice_swe3_4/swe_docu_guidelines.md, doc/website/FAQ.md, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_examples/callbacks/README.md, iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp, iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/callbacks_in_c/ice_c_callbacks_subscriber.c, iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c, iceoryx_examples/ice_access_control/README.md, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_gateway.cpp
The listener examples need to drain the subscriber queue in the callback …
=> iox-#2251 Fix 'Listener' examples

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/test/moduletests/test_vocabulary_span.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/span.inl, iceoryx_hoofs/vocabulary/include/iox/span.hpp
This PR addresses #iox-2253 and makes a few other opportunistic improvements
1. Removes the "End" template on the begin/end constructor per [elBoberido](https://github.com/elBoberido)'s suggestion
2. Adds a number of missing unit test cases for iox::span (informed by coverage reports)
1. [x] Relevant issues are …
=> iox-2253 Fix span assert

.github/workflows/build-test.yml, iceoryx_platform/generic/source/string_.cpp
The `string.cpp` file in the platform abstraction confuses clang-tidy to use the wrong translation unit for the `iox/string.hpp` check. By renaming the file to `string_.cpp` the problem vanishes. …
=> iox-#2011 Rename 'string.cpp' to fix the clang-tidy check

.cirrus.yaml, .github/workflows/build-test.yml
In order to safe credits on Cirrus CI, the FreeBSD build is moved back to github. …
=> iox-#2011 Move FreeBSD back to GitHub actions

iceoryx_posh/cmake/cpptoml/CMakeLists.txt
Backport of https://github.com/eclipse-iceoryx/iceoryx/pull/2261.
See also https://github.com/eclipse-iceoryx/iceoryx/pull/2232#issuecomment-2058987035
1. [x] Assign PR to …
=> iox-#2011 Apply cpptoml patch only if not yet applied

iceoryx_posh/cmake/cpptoml/CMakeLists.txt
The git version on the ROS CI does not support the `quiet` option. This PR make use of cmake mechanisms to suppress to output of 'git apply'. See also #2263 and https://github.com/eclipse-iceoryx/iceoryx/pull/2262#issuecomment-2061430077 …
=> iox-#2011 Use cmake mechanism to suppress the output of 'git apply'

iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp
=> iox-#2266 Removed warning set but not used

.github/workflows/release_build_publish.yml, README.md
The release workflow still used deprecated actions. This PR updates those actions and also fixes the badges after the change of the default branch. Some badges are removed since they are obsolete and do not have a corresponding workflow. …
=> iox-#2011 Update CI Setup and Badges

doc/website/release-notes/.pages, mkdocs.yml, tools/scripts/ice_env.sh, tools/website/export-docu-to-website.sh
It seems I was a little bit too fast with the tag but I don't think we need to re-tag or create a new release.
There was a typo in the `.pages` file for the mkdocs release note generation. …
=> iox-#2282 Fix website for v2.0.6 release notes

iceoryx_platform/.clang-tidy
=> iox-#2011 Remove stale .clang-tidy symlink

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl
GCC 13 (which is in Ubuntu 24.04) introduced a number of false positive warnings when using -Warray-bounds and -Wstring-op; see:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114758
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111118
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110807
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110498
In my testing, these only show up when building with optimizations, i.e. CMAKE_BUILD_TYPE=RelWithDebInfo.
This commit silences those warnings across the two functions that cause the problem, and make the build completely clean.
This should fix the yellow builds in e.g. https://ci.ros2.org/view/packaging/job/packaging_linux/3451/
Note that this targets the `release_2.0` branch, since that is what ROS 2 is currently using.  If you'd like me to target …
=> iox-#2011 Silence some warnings when building with GCC 13.

doc/website/release-notes/iceoryx-unreleased.md, tools/introspection/source/introspection_app.cpp
This PR adds the number of ports to the introspection client display. This makes it easier to get a quick overview over the number of active ports if there are too many to count by hand. …
=> iox-#2299 Add port counts to introspection client

iceoryx_posh/source/popo/publisher_options.cpp, iceoryx_posh/source/popo/subscriber_options.cpp
When building the `iceoryx_hoofs` package from the `release_2.0` branch in Release mode (`-DCMAKE_BUILD_TYPE=Release`), with gcc 13, we get warnings like the following:
```
In file included from /home/ubuntu/rolling_ws/src/eclipse-iceoryx/iceoryx/iceoryx_posh/source/popo/subscriber_options.cpp:17:
In constructor ‘iox::popo::SubscriberOptions::SubscriberOptions(iox::popo::SubscriberOptions&&)’,
inlined from ‘bool iox::cxx::variant<Types>::emplace_at_index(CTorArguments&& ...) [with long unsigned int TypeIndex = 0; CTorArguments = {iox::popo::SubscriberOptions}; Types = {iox::popo::SubscriberOptions, iox::cxx::Serialization::Error}]’ at /home/ubuntu/rolling_ws/install/iceoryx_hoofs/include/iceoryx/v2.0.6/iceoryx_hoofs/internal/cxx/variant.inl:174:5,
inlined from ‘constexpr …
```
=> iox-#2011 Solve a warning when building in Release mode.

README.md
=> iox-#2305 Fix CI badge links and add iceoryx2 reference to the readme

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/include/iceoryx_binding_c/client.h, iceoryx_binding_c/include/iceoryx_binding_c/internal/c2cpp_binding.h, iceoryx_binding_c/include/iceoryx_binding_c/internal/c2cpp_enum_translation.hpp, iceoryx_binding_c/include/iceoryx_binding_c/listener.h, iceoryx_binding_c/include/iceoryx_binding_c/notification_info.h, iceoryx_binding_c/include/iceoryx_binding_c/publisher.h, iceoryx_binding_c/include/iceoryx_binding_c/request_header.h, iceoryx_binding_c/include/iceoryx_binding_c/response_header.h, iceoryx_binding_c/include/iceoryx_binding_c/server.h, iceoryx_binding_c/include/iceoryx_binding_c/service_discovery.h, iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h, iceoryx_binding_c/include/iceoryx_binding_c/user_trigger.h, iceoryx_binding_c/include/iceoryx_binding_c/wait_set.h, iceoryx_binding_c/source/c2cpp_enum_translation.cpp, iceoryx_binding_c/source/c_listener.cpp, iceoryx_binding_c/source/c_service_discovery.cpp, iceoryx_binding_c/source/c_wait_set.cpp
The macros `ENUM` and `CLASS` are very generic names and can potentially cause naming conflicts with user code or other third-party libraries.  These macros are intended to make the headers compatible with both C and C++.  The `ENUM` macro is unnecessary since the `enum` prefix for variable declarations is required in C and optional in C++.  The `CLASS` macro is required to match the Microsoft C++ ABI -- defined as `class` when in C++ mode and `struct` when in C mode.
This PR seeks to solve this by
- Removing the `ENUM` macro, replacing its use with the `enum` keyword.
- Rename `CLASS` macro to `IOX_C_CLASS` to reduce likelihood of naming conflicts
- Command: `sed -i -e 's/\<CLASS\>/IOX_C_CLASS/g' $(find -type f)`
- One file was reverted since `CLASS` was in a comment; not referencing the …
=> iox-#2327 Replace macro ENUM with IOX_ENUM and CLASS with IOX_CLASS

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_sofi.hpp, iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_sofi.inl, iceoryx_hoofs/test/moduletests/test_concurrent_spsc_sofi.cpp
- add comments to clarify concurrent behavior
- fix memory orders
1. [x] All touched (C/C++) source …
=> iox-#2177 Update SPSC SoFi

.github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_platform/win/include/iceoryx_platform/acl.hpp, iceoryx_platform/win/include/iceoryx_platform/mqueue.hpp, iceoryx_platform/win/include/iceoryx_platform/socket.hpp, iceoryx_platform/win/include/iceoryx_platform/types.hpp, iceoryx_platform/win/include/iceoryx_platform/unistd.hpp, iceoryx_platform/win/source/socket.cpp, iceoryx_platform/win/source/unistd.cpp
This change updates the ssize_t type to iox_ssize_t in Windows-specific files to resolve a compatibility issue. It ensures consistent type usage and includes the necessary headers for type definitions. …
=> iox-#2209 Refactor ssize_t to iox_ssize_t for Windows compatibility

.bazelrc, .gitignore, BUILD.bazel, MODULE.bazel, bazel/buildifier_prebuilt/repositories.bzl, bazel/buildifier_prebuilt/setup.bzl, bazel/load_repositories.bzl, bazel/setup_repositories.bzl, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/test/moduletests/test_utility_convert.cpp
=> iox-#2325 support bzlmod

iceoryx_hoofs/concurrent/buffer/source/mpmc_loffli.cpp
fix abaCounter not unique in mpmc_loffli
refer to https://github.com/eclipse-iceoryx/iceoryx/issues/2351 …
=> iox-#2351 fix mpmc_loffli abaCounter not unique

iceoryx_platform/CMakeLists.txt, iceoryx_platform/freertos/cmake/IceoryxPlatformDeployment.cmake, iceoryx_platform/linux/cmake/IceoryxPlatformDeployment.cmake, iceoryx_platform/mac/cmake/IceoryxPlatformDeployment.cmake, iceoryx_platform/qnx/cmake/IceoryxPlatformDeployment.cmake, iceoryx_platform/unix/cmake/IceoryxPlatformDeployment.cmake, iceoryx_platform/win/cmake/IceoryxPlatformDeployment.cmake
The initial PR (#2359) did not propagate the ACL feature flag. This PR fixes the previous error. …
=> iox-#1176 Fix ACL feature flag for cmake builds

MODULE.bazel, doc/website/release-notes/iceoryx-unreleased.md
Currently if you want to depend on Iceoryx as a Bzlmod bazel_dep you have to do something like
```Starlark
bazel_dep(name = "org_eclipse_iceroyx", repo_name = "iceoryx")
git_override(
module_name = "org_eclipse_iceroyx",
commit = "00c5349eabfb1bce5db46efefb39fd9471679be1",
patches = ["//third_party/iceoryx:iceoryx.patch"],
remote = "https://github.com/eclipse-iceoryx/iceoryx",
)
```
It would be nice to fix that typo.
I'll send some follow up PRs to contribute patches that make depending on the module via Bzlmod actually work.
1. [x] Branch follows the naming format …
=> iox-#2364 Fix Bzlmod module name typo

MODULE.bazel, WORKSPACE.bazel, bazel/load_repositories.bzl, bazel/ncurses/ncurses.BUILD, bazel/ncurses/repositories.bzl, doc/website/release-notes/iceoryx-unreleased.md, tools/introspection/BUILD.bazel, tools/introspection/include/iceoryx_introspection/introspection_app.hpp
Depend on third-party `@ncurses` when building with Bazel. This is easy with Bzlmod, but I went the hard path and made it work for legacy Workspace as well.
Testing:
```console
❯ bazel run //tools/introspection:iox-introspection-client --enable_bzlmod --noenable_workspace -- --version
INFO: Analyzed target //tools/introspection:iox-introspection-client (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tools/introspection:iox-introspection-client up-to-date:
bazel-bin/tools/introspection/iox-introspection-client
INFO: Elapsed time: 0.061s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/tools/introspection/iox-introspection-client --version
Latest official iceoryx release …
```
=> iox-#2372: Depend on @ncurses when building with Bazel

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_platform/win/source/time.cpp
I am a member of Microsoft vcpkg, due to there are new changes merged by microsoft/STL#5105, which revealed a conformance issue in `iceoryx`. It must add include `<chrono>` to fix this error.
Compiler error with this STL change:
```
D:\b\iceoryx\src\v2.0.6-c8abea20ae.clean\iceoryx_platform\win\source\time.cpp(42): error C2039: 'system_clock': is not a member of 'std::chrono'
```
- Follow the …
=> iox-#2377: Include `<chrono>` for system_clock

.github/workflows/build-test.yml
The CI upgraded bazel to v8.0.0 and this breaks the bazel setup. We currently support only bazel up to v7.4.1. …
=> iox-#2011 Pin bazel to v7.4.1 on CI

doc/website/concepts/architecture.md, doc/website/release-notes/iceoryx-unreleased.md
=> iox-#2390 Fixes typo in architecture.md

iceoryx_hoofs/concurrent/sync/include/iox/spin_lock.hpp
With the introduction of clang-tidy 18, a new warning was found. This PR fixes that warning. …
=> iox-#2011 Fix clang-tidy warning

doc/website/release-notes/iceoryx-unreleased.md
- Minor fixes in release notes
[eca]: …
=> Minor fixes in release notes

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/platform/win/source/time.cpp
Not including this header leads to compilation errors about missing symbols/templates under VS2022 on Windows. …
=> iox-#2420 Add missing header <chrono>

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/gateway/channel.hpp, iceoryx_posh/include/iceoryx_posh/internal/gateway/channel.inl, iceoryx_posh/test/moduletests/test_gw_channel.cpp
This PR replaces the call to the non-existing `getService` in the comparison operator of `Channel` with `getServiceDescription`. Another option would be to remove the comparison operator completely …
=> iox-#2426 Fix comparison operator in channel.inl

.github/workflows/build-test.yml, .github/workflows/release_build_publish.yml
From April 1st, Ubuntu 20.04 will not be supported anymore. This PR updates all Ubuntu Jobs to Ubuntu 24.04, except the integrationtests and code coverage jobs, which still rely on Ubuntu 22.04.
The standard Ubuntu job does now build with the standard gcc and cmake. Previously it tried to simulate a QNX build but that is not possible anymore since the old gcc is not supported on a newer Ubuntu. We still have the cirrus CI setup to simulate the QNX setup.
1. [x] Commits messages are according to …
=> iox-#2011 Update Ubuntu on CI

MODULE.bazel
Rename Bzlmod module to `iceoryx` as per https://github.com/eclipse-iceoryx/iceoryx/issues/2435 to follow conventions and make it easier to consume the repo as Bzlmod library.
Holding off with the changelog commit to avoid merge conflicts. …
=> iox-#2435: Rename Bzlmod module to `iceoryx`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/reporting/include/iox/assertions.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/error_forwarding.hpp, iceoryx_hoofs/reporting/include/iox/error_reporting/source_location.hpp
This fixes a compile error for the iceoryx2 C++ bindings when used with gcc 8 …
=> iox-#2480 Fix gcc 8 compile error
