eclipse-iceoryx/iceoryx

tools/run_all_tests.sh
Signed-off-by: sagniknitr <basusagnik1995@gmail.com>
=> Fix in run_all_test.sh shell script file

README.md
fixes https://github.com/eclipse/iceoryx/issues/8
Signed-off-by: Knese Karsten karsten.knese@us.bosch.com
=> mention colcon in install instructions

iceoryx_posh/source/roudi/roudi_process.cpp
=> iox-#23 fixed response generation for runnable creation

iceoryx_posh/CMakeLists.txt, iceoryx_utils/CMakeLists.txt, tools/introspection/CMakeLists.txt
=> release 0.16.0

iceoryx_examples/icecrystal/Readme.md, iceoryx_posh/source/roudi/roudi_process.cpp
=> merged lost changes

iceoryx_posh/include/iceoryx_posh/internal/runtime/message_queue_interface.hpp, iceoryx_posh/test/moduletests/test_mq_interface.cpp
Signed-off-by: Christian Eltzschig <christian.eltzschig2@de.bosch.com>
=> iox-#56 removed move assignment and ctor

iceoryx_posh/CMakeLists.txt
=> iox-#67: QUIET for cpptoml_vendor

iceoryx_posh/CMakeLists.txt, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/source/mepoo/mepoo_config.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_posh_senderport.cpp
=> iox-#78: adaptations for reduction of memory consumption

CONTRIBUTING.md, README.md
=> Add iceoryx usage table

iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp, iceoryx_posh/source/mepoo/chunk_header.cpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/optional.inl, iceoryx_utils/include/iceoryx_utils/internal/cxx/vector.inl, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/allocator.hpp, iceoryx_utils/source/posix_wrapper/shared_memory_object/allocator.cpp, iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp, iceoryx_utils/test/moduletests/test_allocator.cpp
=> Iox #76 remove const cast wherever possible

iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp
=> iox-#113 cleanup shared memory at restart after an anomaly

iceoryx_posh/cmake/iceoryx_versions.hpp.in, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_multi_process.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp, iceoryx_posh/source/popo/sender_port.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/roudi_multi_process.cpp, iceoryx_posh/source/roudi/roudi_process.cpp, iceoryx_utils/source/error_handling/error_handling.cpp, tools/introspection/source/introspection_app.cpp
removes the last remaining simplelogger calls and replaces them with the new logger
=> Iox #88 remove simplelogger calls

iceoryx_meta/CMakeLists.txt, iceoryx_posh/CMakeLists.txt, iceoryx_utils/CMakeLists.txt, iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.inl, iceoryx_utils/test/moduletests/test_posix_timer.cpp
=> Iox #120 fix sporadic timing test failure

iceoryx_utils/test/moduletests/test_posix_timer.cpp
=> iox-#120 fix DestructorIsBlocking timer test

iceoryx_utils/include/iceoryx_utils/internal/units/duration.hpp, iceoryx_utils/include/iceoryx_utils/internal/units/duration.inl
=> iox-#92 Clean up code to follow the coding rule

iceoryx_posh/include/iceoryx_posh/internal/popo/receiver_port.hpp, iceoryx_utils/test/moduletests/test_index_queue.cpp, iceoryx_utils/test/moduletests/test_lockfree_queue_cyclic_index.cpp, iceoryx_utils/test/moduletests/test_semaphore_module.cpp
=> Iox #143 make receiver port subscribe virtual

iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
=> iox-#85 remove blinking roudi warning

tools/docker/README.md
Signed-off-by: Christian Eltzschig <christian.eltzschig2@de.bosch.com>
=> iox-#156: updated paths in docker readme

iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi_multi_process.hpp, iceoryx_posh/source/roudi/roudi_multi_process.cpp
Later startup of Roudi Message Queue Thread
=>  iox-#171 added option to defer mq thread startup

iceoryx_posh/include/iceoryx_posh/internal/capro/capro_message.hpp, iceoryx_posh/source/capro/capro_message.cpp, iceoryx_posh/test/moduletests/test_capro_message.cpp
adding unittests for capro message class.
=> Iox #168 unit test for capro message

iceoryx_utils/include/iceoryx_utils/cxx/variant_queue.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/variant_queue.inl, iceoryx_utils/test/moduletests/test_cxx_variant_queue.cpp
Integrate MultiPusherMultiConsumer queue in VariantQueue
=> Iox #25 Integrate MPMC queue in VariantQueue

iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_popper.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp, iceoryx_posh/source/popo/delivery_fifo.cpp, iceoryx_posh/source/popo/ports/subscriber_port_user.cpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp, iceoryx_utils/include/iceoryx_utils/cxx/variant_queue.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/fifo.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/fifo.inl, iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/sofi.inl, iceoryx_utils/include/iceoryx_utils/internal/cxx/variant_queue.inl, iceoryx_utils/test/moduletests/test_concurrent_sofi.cpp
* Use `setCapactity()`
* Use `uint64_t`
=> Iox #25 queue harmonization

.github/workflows/build-test.yml, tools/iceoryx_build_test.sh, tools/run_all_tests.sh
Signed-off-by: Ithier Jeff (CC-AD/EYF1) <jeff.ithier@de.bosch.com>
=> iox-#234 Only run DDS tests when DDS Gateway is built.

iceoryx_posh/test/moduletests/test_posh_runtime.cpp
Signed-off-by: Christian Eltzschig <christian.eltzschig2@de.bosch.com>
Fixes #250
=> iox-#250 adjusted test fixture to timing test

iceoryx_meta/CMakeLists.txt, iceoryx_posh/CMakeLists.txt, iceoryx_utils/CMakeLists.txt, tools/introspection/CMakeLists.txt
increase version number in CMake for release 0.17 branch
=> iox-#248 increase cmake version to 0.17.0.7

iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/subscriber_port_user.hpp, iceoryx_posh/source/popo/ports/subscriber_port_user.cpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
Integration test for subscriber port and publisher port. Single and multi producer.
=> Iox #25 add integration test pubsub port user

CONTRIBUTING.md, PLANNED_FEATURES.md, README.md, doc/conceptual-guide.md, doc/goals-non-goals.md, doc/installation-guide.md, doc/usage-guide.md, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp
Gitter badge and some main-README updates
=> Iox #136 gitter badge

iceoryx_examples/iceperf/CMakeLists.txt
=> Iox #238 iceperf qnx

iceoryx_utils/include/iceoryx_utils/cxx/string.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/string.inl, iceoryx_utils/test/moduletests/test_cxx_string.cpp
=> Iox #264 fix char array assignment to cxx string for v0.17

iceoryx_utils/include/iceoryx_utils/log/logger.hpp, iceoryx_utils/include/iceoryx_utils/log/logging.hpp, iceoryx_utils/source/log/logger.cpp, iceoryx_utils/test/moduletests/test_logger.cpp
code contributed by @prasannabhat and @nihalchari
=> Iox #278 logger add is enabled

README.md
fix typo in link
Signed-off-by: bishibashiB <b.eickhoff@gmx.de>
=> iox-#238 fix badge link

iceoryx_utils/test/stresstests/test_stress_sofi.cpp
This is a follow up PR for https://github.com/eclipse/iceoryx/pull/145. That one has to be merged first
=> Iox #115 add sofi stresstests review findings

iceoryx_posh/cmake/iceoryx_poshConfig.cmake, iceoryx_posh/cmake/iceoryx_posh_deployment.cmake, iceoryx_posh/cmake/iceoryxversions.cmake, iceoryx_posh/cmake/install_help_and_config.cmake, iceoryx_posh/test/integrationtests/service_discovery/test_roudi_service_discovery.hpp, iceoryx_utils/cmake/IceoryxPackageHelper.cmake, iceoryx_utils/cmake/IceoryxPlatformDetection.cmake, iceoryx_utils/cmake/iceoryx_utilsConfig.cmake, iceoryx_utils/cmake/iceoryx_utils_testingConfig.cmake, iceoryx_utils/source/cxx/helplets.cpp, tools/introspection/cmake/iceoryx_introspectionConfig.cmake
Add copyright header to all files mentioned.
=> iox-#338: Add copyright header

CONTRIBUTING.md
Update the CONTRIBUTING.md for multiple copyright owners.
Signed-off-by: Mathias Kraus <mathias.kraus@apex.ai>
=> iox-#355 update CONTRIBUTING.md for multiple copyright owners

.github/PULL_REQUEST_TEMPLATE/development.md, CONTRIBUTING.md
- This PR's description is an example of the PR template in action 😉 
1. [x] Merge
- Closes #358
=> iox-#358 Add PR template for code contributions

tools/run_all_tests.sh
Signed-off-by: Prasanna Bhat <prasanna.yoga@gmail.com>
`;&` operator enables fall through in case statement in shell script.
[This operator](https://stackoverflow.com/questions/12010686/case-statement-fallthrough) was introduced in bash 4.0.
**NOTE :** This change is …
=> Iox #398 fix bug in run_all_tests.sh

CONTRIBUTING.md, GOVERNANCE.md, README.md
To simplify the coordination of the iceoryx development, I propose to have a bi-weekly meeting. @ariexi proposed a Zoom meeting. I like the idea as the other Eclipse workings groups are also using Zoom and we can reuse the infrastructure. The link will be added later.
1. …
=> iox-#356 Add proposal for iceoryx developer meetup

iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/base_publisher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/publisher_port_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/typed_publisher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_publisher.inl, iceoryx_posh/include/iceoryx_posh/popo/base_publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp, iceoryx_posh/include/iceoryx_posh/popo/typed_publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/untyped_publisher.hpp, iceoryx_posh/include/iceoryx_posh/roudi/port_pool.hpp, iceoryx_posh/source/popo/ports/publisher_port_data.cpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/source/roudi/port_pool.cpp, iceoryx_posh/source/version/version_info.cpp, iceoryx_posh/test/mocks/publisher_mock.hpp, iceoryx_posh/test/moduletests/test_base_port.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
Introduce `PublisherOption` struct to pass options like history size to the publisher.
1. [ ] Merge
- Partly closes #408
=> Iox #408 add struct with options to publisher

iceoryx_binding_c/test/moduletests/test_event_info.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_distributor.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_pusher.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_queue_types.hpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_queue.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp, iceoryx_utils/include/iceoryx_utils/cxx/variant_queue.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/variant_queue.inl, iceoryx_utils/test/moduletests/test_cxx_variant_queue.cpp
1. [ ] All checks have passed
1. [ ] Merge
- Closes #456
=> iox-#456 fixed and tested variant queue chunk lost bug

doc/design/chunk_header.md, iceoryx_dds/include/iceoryx_dds/internal/gateway/iox_to_dds.inl, iceoryx_dds/test/mocks/chunk_mock_dds.hpp, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_gateway.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/typed_mem_pool.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/chunk_sender.inl, iceoryx_posh/include/iceoryx_posh/mepoo/chunk_header.hpp, iceoryx_posh/source/mepoo/chunk_header.cpp, iceoryx_posh/source/mepoo/memory_manager.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_port.cpp
Signed-off-by: Mathias Kraus <mathias.kraus@apex.ai>
Remove `m_` prefix from public ChunkHeader members
1. [ ] Merge
- Partly-closes #14
=> iox-#14 remove `m_` prefix form public ChunkHeader members

CONTRIBUTING.md, GOVERNANCE.md, NOTICE.md, README.md, doc/aspice_swe3_4/swe_docu_guidelines.md, doc/website/FAQ.md, doc/website/getting-started/installation.md, iceoryx_binding_c/include/iceoryx_binding_c/types.h, tools/docker/README.md
Updating all URLs in iceoryx to new organization
1. [ ] Merge
- Closes #467
=> Iox #467 move iceoryx into iceoryx eclipse org

CONTRIBUTING.md, doc/website/advanced/installation-guide-for-contributors.md, tools/iceoryx_build_test.sh
This PR improves the documentation for doing gcov and sanitizer scans and the build script.
1. [ ] Merge
- Closes #497
=> Iox #497 static build docu gcov

CONTRIBUTING.md
This is the proposal for the new Copyright Header standard in iceoryx.
1. [x] Merge
- Partly Closes #483 
@mossmaurice @elBoberido @elfenpiff …
=> Iox #483 Copyright Header Contributing.md

iceoryx_utils/include/iceoryx_utils/cxx/generic_raii.hpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/memory_map.hpp, iceoryx_utils/include/iceoryx_utils/internal/posix_wrapper/shared_memory_object/shared_memory.hpp, iceoryx_utils/source/cxx/generic_raii.cpp, iceoryx_utils/source/posix_wrapper/shared_memory_object/memory_map.cpp, iceoryx_utils/source/posix_wrapper/shared_memory_object/shared_memory.cpp, iceoryx_utils/test/moduletests/test_cxx_generic_raii.cpp
1. [x] Merge
fixes partially #542
=> Iox #542 resource leak fix

iceoryx_utils/CMakeLists.txt, iceoryx_utils/include/iceoryx_utils/posix_wrapper/signal_handler.hpp, iceoryx_utils/source/posix_wrapper/signal_handler.cpp, iceoryx_utils/test/moduletests/test_posix_signal_handler.cpp
1. [x] Merge
- Partially closes #542
=> Iox #542 sigaction abstraction

iceoryx_utils/include/iceoryx_utils/cxx/vector.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/vector.inl, iceoryx_utils/test/moduletests/test_cxx_vector.cpp
=> iox-#568 elements are cleaned up in reverse order in vector

iceoryx_utils/include/iceoryx_utils/internal/cxx/variant.inl, iceoryx_utils/test/moduletests/test_cxx_variant.cpp
=> iox-#570 fixed variant move ctor and assignment behavior

iceoryx_utils/include/iceoryx_utils/design_pattern/creation.hpp
=> iox-#542 creation pattern detailed doxygen docu

doc/website/getting-started/installation.md, iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/runtime/posh_runtime.cpp, iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp, iceoryx_utils/include/iceoryx_utils/error_handling/error_handling.hpp
* Update installation guide
* Add warning print on 32-bit systems
1. [x] All checkboxes in the PR checklist are checked or …
=> iox-#549 Add requirement for 64-bit system and warning on 32-bit systems

iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp, iceoryx_posh/CMakeLists.txt, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_listener.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_notifier.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/event_variable_data.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl, iceoryx_posh/include/iceoryx_posh/popo/event_attorney.hpp, iceoryx_posh/include/iceoryx_posh/popo/listener.hpp, iceoryx_posh/source/popo/building_blocks/event_listener.cpp, iceoryx_posh/source/popo/building_blocks/event_notifier.cpp, iceoryx_posh/source/popo/listener.cpp, iceoryx_posh/test/moduletests/test_popo_event_variable.cpp, iceoryx_posh/test/moduletests/test_popo_listener.cpp
=> Iox #350 rename active call set into listener

iceoryx_utils/include/iceoryx_utils/cxx/function_ref.hpp, iceoryx_utils/include/iceoryx_utils/cxx/type_traits.hpp, iceoryx_utils/include/iceoryx_utils/internal/cxx/expected.inl, iceoryx_utils/test/moduletests/test_cxx_expected.cpp, iceoryx_utils/test/moduletests/test_cxx_type_traits.cpp
=> iox-#599 check callables of-expected and then or else

iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.inl, iceoryx_posh/test/moduletests/test_popo_listener.cpp, iceoryx_posh/test/moduletests/test_popo_used_chunk_list.cpp
=> Iox #623 use 8 byte type for chunk management pointer and add tests

iceoryx_posh/test/CMakeLists.txt, iceoryx_posh/test/moduletests/test_popo_toml_gateway_config_parser.cpp, iceoryx_posh/test/moduletests/test_roudi_config_toml_file_provider.cpp
=> iox-#650 generate the test_input_path.hpp file in the build folder

iceoryx_binding_c/include/iceoryx_binding_c/publisher.h, iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h, iceoryx_binding_c/source/c_publisher.cpp, iceoryx_binding_c/source/c_subscriber.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_examples/icedelivery/iox_publisher_with_options.cpp, iceoryx_examples/icedelivery/iox_subscriber_with_options.cpp, iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp, iceoryx_posh/include/iceoryx_posh/roudi/port_pool.inl, iceoryx_posh/source/popo/ports/publisher_port_data.cpp, iceoryx_posh/source/popo/ports/subscriber_port_data.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/runtime/posh_runtime.cpp, iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp
=> Iox #615 block publisher when subscriber queue full

iceoryx_integrationtest/iceoryx_integrationtest/test_roudi_startup_shutdown.py, iceoryx_posh/include/iceoryx_posh/internal/roudi/roudi.hpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
1. [x] All required checks have passed (except `task-list-completed`) …
=> Iox #615 unblock roudi shutdown with blocked publisher

iceoryx_examples/waitset/CMakeLists.txt, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_basic.cpp
=> Iox #679 create introductory example of the waitset

iceoryx_meta/build_options.cmake
For technical debt.
[contributing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/CONTRIBUTING.md#co …
=> iox #709 remove duplicate cmake option.

iceoryx_binding_c/source/c_wait_set.cpp, iceoryx_binding_c/test/moduletests/test_event_info.cpp, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_basic.cpp, iceoryx_examples/waitset/ice_waitset_gateway.cpp, iceoryx_examples/waitset/ice_waitset_sync.cpp, iceoryx_examples/waitset/ice_waitset_trigger.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/event_callback.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/event_info.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/trigger.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/wait_set.inl, iceoryx_posh/include/iceoryx_posh/popo/event_callback.hpp, iceoryx_posh/include/iceoryx_posh/popo/event_info.hpp, iceoryx_posh/include/iceoryx_posh/popo/listener.hpp, iceoryx_posh/include/iceoryx_posh/popo/trigger.hpp, iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp, iceoryx_posh/source/popo/event_info.cpp, iceoryx_posh/source/popo/listener.cpp, iceoryx_posh/test/moduletests/test_popo_event_info.cpp, iceoryx_posh/test/moduletests/test_popo_trigger.cpp, iceoryx_posh/test/moduletests/test_popo_user_trigger.cpp, iceoryx_posh/test/moduletests/test_popo_waitset.cpp, iceoryx_utils/include/iceoryx_utils/cxx/helplets.hpp
=> Iox #707 extend waitset callback for user type

iceoryx_binding_c/include/iceoryx_binding_c/listener.h, iceoryx_binding_c/include/iceoryx_binding_c/wait_set.h, iceoryx_binding_c/source/c_listener.cpp, iceoryx_binding_c/source/c_wait_set.cpp, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, iceoryx_examples/callbacks/README.md, iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp, iceoryx_examples/callbacks_in_c/CMakeLists.txt, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_gateway.cpp, iceoryx_examples/waitset_in_c/README.md, iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c, iceoryx_posh/include/iceoryx_posh/popo/listener.hpp, iceoryx_posh/include/iceoryx_posh/popo/wait_set.hpp
=> Iox #707 extend binding c to callback extensions

iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/subscriber.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/untyped_subscriber.inl, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp, iceoryx_posh/include/iceoryx_posh/popo/untyped_subscriber.hpp, iceoryx_posh/test/integrationtests/test_popo_pub_sub_listener.cpp, iceoryx_posh/test/mocks/subscriber_mock.hpp
=> Iox #714 call reset in subscriber destructor

iceoryx_examples/callbacks/README.md, iceoryx_examples/callbacks/ice_callbacks_listener_as_class_member.cpp, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c, iceoryx_examples/ice_access_control/README.md, iceoryx_examples/icecrystal/Readme.md, iceoryx_examples/icedelivery/README.md, iceoryx_examples/icedelivery_in_c/README.md, iceoryx_examples/iceensemble/README.md, iceoryx_examples/icehello/README.md, iceoryx_examples/iceoptions/README.md, iceoryx_examples/singleprocess/README.md, iceoryx_examples/waitset/README.md, iceoryx_examples/waitset_in_c/README.md, tools/introspection/source/introspection_app.cpp
=> Iox #482 Add asciinema recordings merge to master

iceoryx_utils/README.md, iceoryx_utils/include/iceoryx_utils/cxx/attributes.hpp
=> iox-#743 added attributes.hpp documentation in utils overview

iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, iceoryx_posh/test/moduletests/test_popo_listener.cpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.hpp, iceoryx_utils/include/iceoryx_utils/internal/concurrent/smart_lock.inl, iceoryx_utils/test/moduletests/test_concurrent_smart_lock.cpp
=> Iox #588 module tests for smart lock

CONTRIBUTING.md, README.md, doc/goals-non-goals.md, doc/website/getting-started/installation.md, doc/website/getting-started/overview.md, iceoryx_examples/icedelivery/README.md, iceoryx_integrationtest/Readme.md
=> iox-#762 add space between 'ROS' and '2'

tools/list_stl_dependencies.sh
=> iox-#765 list stl dependencies with bash script

doc/website/getting-started/installation.md
=> iox-#33 add installation guide for Windows

CONTRIBUTING.md, README.md
=> iox-#425 Update and align quality levels with ROS quality levels

doc/design/listener.md
=> Iox #350 listener design document

.github/workflows/build-test.yml, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/signal.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp, iceoryx_hoofs/platform/win/source/mman.cpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/platform/win/source/semaphore.cpp, iceoryx_hoofs/platform/win/source/signal.cpp, iceoryx_hoofs/platform/win/source/time.cpp, iceoryx_hoofs/platform/win/source/unistd.cpp, iceoryx_hoofs/platform/win/source/win32_errorHandling.cpp
=> Iox #33 implement signal handler for windows 10

iceoryx_posh/include/iceoryx_posh/popo/publisher.hpp, iceoryx_posh/include/iceoryx_posh/popo/subscriber.hpp
=> iox-#768 Backport: Add missing template parameter for user-header to typed C++ API

.clang-format, CONTRIBUTING.md, doc/aspice_swe3_4/example/iceoryx_component/source/example_module/example_base_class.hpp, doc/website/advanced/installation-guide-for-contributors.md, iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp, tools/git-hooks/Readme.md, tools/git-hooks/commit-msg, tools/git-hooks/pre-commit, tools/git-hooks/prepare-commit-msg
Add hooks to enforce style rules for formatted commit messages and code.
[eca]: …
=> iox-#486 Add git commit hooks

iceoryx_posh/cmake/cpptoml/0001-Add-include-limits-to-port-to-GCC-11.patch, iceoryx_posh/cmake/cpptoml/cpptoml.cmake.in
Signed-off-by: Homalozoa <nx.tardis@gmail.com> …
=> iox-#811 Add patch to port to GCC 11

.github/workflows/integrationtest.yml
=> iox-#825 update ROS setup in Github CI

.github/workflows/integrationtest.yml
=> [Backport release-1.0] iox-#825 update ROS setup in Github CI

iceoryx_posh/include/iceoryx_posh/runtime/posh_runtime.hpp, iceoryx_posh/test/mocks/posh_runtime_mock.hpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/testing/roudi_environment/runtime_test_interface.cpp
=> Iox #449 create posh runtime mock

iceoryx_binding_c/include/iceoryx_binding_c/service_description.h, iceoryx_binding_c/source/cpp2c_service_description_translation.cpp, iceoryx_binding_c/test/moduletests/test_cpp2c_service_description_translation.cpp, iceoryx_binding_c/test/moduletests/test_publisher.cpp, iceoryx_binding_c/test/moduletests/test_subscriber.cpp, iceoryx_posh/cmake/iceoryx_posh_deployment.cmake, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port_data.hpp, iceoryx_posh/source/capro/service_description.cpp, iceoryx_posh/source/popo/ports/interface_port_data.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/integrationtests/test_roudi_findservice.cpp, iceoryx_posh/test/moduletests/test_base_port.cpp, iceoryx_posh/test/moduletests/test_capro_message.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp, iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp
=> Iox #415 Refactor Service Description Part1: Remove integers values

iceoryx_meta/CMakeLists.txt
=> iox-#777 Set CMAKE_INSTALL_RPATH only when shared library is built

iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_internal.hpp, iceoryx_hoofs/test/moduletests/test_cxx_variant.cpp
=> Iox #415 Add generic constructor to `cxx::variant`

iceoryx_hoofs/include/iceoryx_hoofs/internal/objectpool/objectpool.hpp, iceoryx_hoofs/test/moduletests/test_objectpool.cpp
* Add protected accessors for m_first and m_last
* Make nextFree protected
* Fix two tests that access private members by using derived struct …
=> iox-#529 Remove define private public from test_objectpool

iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
* Use real subscriber to get introspection data (slows down a test
unfortunately) instead of internal class members …
=> iox-#529 Remove define private from mepoo test

.github/workflows/build-test.yml, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/static_storage.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant.inl, iceoryx_hoofs/test/moduletests/test_static_storage.cpp, iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/source/capro/service_description.cpp, tools/check_formatting.sh
=> Add clang format ci job

iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp
Due to merging order there are now improperly formatted file in the master, so fix it
See [latest build failed](https://github.com/eclipse-iceoryx/iceoryx/commits/master)
1. [x] …
=> iox-#887 Fix improperly formatted test_posh_mepoo.cpp

tools/introspection/source/introspection_app.cpp
1. [X] Code follows the coding style of [CONTRIBUTING.md][contributing]
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Update the PR title
1. [X] Relevant issues are linked
1. [X] Add sensible notes for the reviewer
1. [X] All checks have passed (except `task-list-completed`)
1. [X] Assign PR to reviewer …
=> iox-#960 Fix format string issues

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp, iceoryx_posh/source/runtime/ipc_interface_creator.cpp
1. [X] Tests follow the [best practice for testing][testing]
1. [X] Commits messages are according to this [guideline][commit-guidelines]
1. [X] Update the PR title
1. [X] Relevant issues are linked
1. [X] Add sensible notes for the reviewer
1. [X] All checks have passed (except `task-list-completed`)
1. [X] Assign PR to reviewer …
=> iox-#962 Fix typos

CHANGELOG.md, doc/goals-non-goals.md
Signed-off-by: Felix Bier <flx.bier@gmail.com>
[eca]: …
=> iox-#968: Fix typos in goals/non-goals section

CHANGELOG.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp, iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
=> iox-#992 Add templated from/into free functions for conversions

CHANGELOG.md, doc/website/advanced/how-optional-and-error-values-are-returned-in-iceoryx.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl, iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp, iceoryx_hoofs/test/stresstests/benchmark_optional_and_expected/benchmark_optional_and_expected.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_mepoo_typed_mempool.cpp
=> Iox #987 remove the requirement of invalid state from cxx expected

CHANGELOG.md, iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/platform/CMakeLists.txt
=> iox-#1013 Split iceoryx_platform cmake code into own file

CHANGELOG.md, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp
=> Iox #415 remove offer from service discovery

CHANGELOG.md, doc/website/FAQ.md, doc/website/advanced/installation-guide-for-contributors.md, tools/ice_env.sh, tools/scripts/ice_env.sh
=> Iox #1049 create iceoryx docker shell script

iceoryx_hoofs/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/units/duration.inl, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/timer.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/grp.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pwd.hpp, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/win32_errorHandling.hpp, iceoryx_hoofs/platform/win/source/semaphore.cpp, iceoryx_hoofs/platform/win/source/win32_errorHandling.cpp, iceoryx_hoofs/source/posix_wrapper/timer.cpp, iceoryx_hoofs/test/moduletests/test_ipc_channel.cpp, iceoryx_hoofs/test/moduletests/test_unit_duration.cpp, iceoryx_posh/source/roudi/memory/memory_provider.cpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp, iceoryx_posh/test/moduletests/test_mepoo_chunk_header.cpp
=> iox-#1076 Introduce `cxx::invoke_result` to solve the deprecated `std::result_of` problem

iceoryx_posh/include/iceoryx_posh/internal/roudi/service_registry.hpp, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/roudi/service_registry.cpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp, iceoryx_posh/test/moduletests/test_roudi_service_registry.cpp
=> Iox #415 additional find service method

CHANGELOG.md, doc/website/FAQ.md, iceoryx_examples/singleprocess/CMakeLists.txt, iceoryx_posh/test/CMakeLists.txt
=> iox-#1082 Set stack size for singleprocess example

.github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp, iceoryx_posh/include/iceoryx_posh/gateway/gateway_discovery.hpp, tools/scripts/clang_tidy_check.sh
=> Iox #299 Clang-Tidy Pull-Request job

iceoryx_posh/source/roudi/port_manager.cpp
=> iox-#27 Fix lambda this capturing

CONTRIBUTING.md, doc/website/examples/icediscovery.md, doc/website/getting-started/examples/icediscovery.md, doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_examples/README.md, iceoryx_examples/icediscovery/CMakeLists.txt, iceoryx_examples/icediscovery/README.md, iceoryx_examples/icediscovery/iox_find_service.cpp, iceoryx_examples/icediscovery/iox_offer_service.cpp, iceoryx_integrationtest/CMakeLists.txt, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_example.py, iceoryx_meta/CMakeLists.txt, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp
=> iox-#415 Add functional find service example

doc/website/release-notes/iceoryx-v1-0-0.md, doc/website/release-notes/iceoryx-v2-0-0.md
Signed-off-by: Dietrich Kroenke <dietrich.kroenke@apex.ai> …
=> iox-#1126 Add missing entries to iceoryx 2.0 changelog

iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/base_client.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/base_server.inl, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/client_server_port_types.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/mocks/base_port_mock.hpp, iceoryx_posh/test/mocks/client_mock.hpp, iceoryx_posh/test/mocks/server_mock.hpp, iceoryx_posh/test/mocks/trigger_handle_mock.hpp
=> Iox #27 create mocks for client and server port

iceoryx_binding_c/CMakeLists.txt, iceoryx_binding_c/include/iceoryx_binding_c/api.h, iceoryx_binding_c/include/iceoryx_binding_c/request_header.h, iceoryx_binding_c/include/iceoryx_binding_c/response_header.h, iceoryx_binding_c/source/c_request_header.cpp, iceoryx_binding_c/source/c_response_header.cpp, iceoryx_binding_c/test/moduletests/test_request_header.cpp, iceoryx_binding_c/test/moduletests/test_response_header.cpp
=> Iox #27 create rpc header c binding

.clang-tidy, doc/website/examples/.pages, doc/website/examples/icediscovery_in_c.md, iceoryx_binding_c/include/iceoryx_binding_c/config.h, iceoryx_binding_c/include/iceoryx_binding_c/service_description.h, iceoryx_binding_c/test/moduletests/test_config.cpp, iceoryx_binding_c/test/moduletests/test_service_description.cpp, iceoryx_examples/README.md, iceoryx_examples/icediscovery_in_c/CMakeLists.txt, iceoryx_examples/icediscovery_in_c/README.md, iceoryx_examples/icediscovery_in_c/iox_c_find_service.c, iceoryx_examples/icediscovery_in_c/iox_c_offer_service.c, iceoryx_examples/icediscovery_in_c/sleep_for.h, iceoryx_integrationtest/CMakeLists.txt, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_in_c_example.py, iceoryx_meta/CMakeLists.txt
=> Iox #1142 icediscovery in c

CONTRIBUTING.md
=> iox-#743 improve contributing md

NOTICE.md
=> Iox #743 validate notice

iceoryx_integrationtest/Readme.md
Correct spelling mistakes, add new lines, update output snippets
[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-message …
=> iox-#743 Update integration test readme

doc/design/error-handling.md
=> iox-#743 doc design error handling review

iceoryx_examples/complexdata/README.md
Signed-off-by: Marika Lehmann <marika.lehmann@apex.ai> …
=> iox-#743 Validate complexdata example

doc/design/README.md, doc/design/draft/README.md
=> iox-#743 doc design root readme review

QUALITY_DECLARATION.md
=> iox-#743  iox-#743 Update quality declaration

doc/website/examples/.pages, doc/website/examples/request_response.md, doc/website/examples/request_response_in_c.md, iceoryx_examples/README.md, iceoryx_examples/request_response/README.md, iceoryx_examples/request_response_in_c/README.md
[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-message …
=> iox-#743 Make example table and navi consistent

iceoryx_examples/user_header/README.md, iceoryx_examples/user_header/publisher_cxx_api.cpp, iceoryx_examples/user_header/subscriber_cxx_api.cpp
=> iox-#743 review user header example

iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp, iceoryx_hoofs/platform/win/source/file.cpp, iceoryx_hoofs/source/posix_wrapper/file_lock.cpp, tools/scripts/clang_tidy_check.sh
=> iox-#1216 enable unlock file functionality in windows platform

iceoryx_examples/icedelivery/README.md, iceoryx_examples/icedelivery/iox_publisher.cpp
Signed-off-by: Marika Lehmann <marika.lehmann@apex.ai> …
=> iox-#743 Validation of icedelivery example

iceoryx_examples/icedelivery_in_c/README.md, iceoryx_examples/icedelivery_in_c/ice_c_publisher.c, iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c
=> iox-#743 Validation of icedelivery_in_c example

doc/design/relocatable_pointer.md
=> iox-#743 Update relocatable_pointer.md

doc/design/lockfree_queue.md
=> iox-#743 Update lock-free queue design

cmake/cyclonedds/cyclonedds-cxx.cmake.in, cmake/cyclonedds/cyclonedds.cmake.in, doc/website/release-notes/iceoryx-v2-0-0.md
=> iox-#1223 Fix dds gateway failure

iceoryx_binding_c/README.md, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/waitset_in_c/README.md
=> Iox #743 update binding c documentation for heap usage

iceoryx_dds/CMakeLists.txt, tools/introspection/CMakeLists.txt
=> iox-#1194 Unique include path for introspection dds gateway

iceoryx_examples/waitset/README.md, iceoryx_examples/waitset/ice_waitset_gateway.cpp, iceoryx_examples/waitset/ice_waitset_grouping.cpp, iceoryx_examples/waitset/ice_waitset_individual.cpp, iceoryx_examples/waitset/ice_waitset_publisher.cpp, iceoryx_examples/waitset/ice_waitset_timer_driven_execution.cpp, iceoryx_examples/waitset/ice_waitset_trigger.cpp
=> iox-#743 Validation of waitset example

iceoryx_hoofs/test/integrationtests/test_lockfree_queue_stresstest.cpp, iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/barrier.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/port_manager.hpp, iceoryx_posh/source/roudi/port_manager.cpp
=> iox-#1230 Introduce barrier in queue stress tests

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
=> iox-#1239 Fix string compiler warning

iceoryx_examples/request_response/README.md, iceoryx_examples/request_response/client_cxx_waitset.cpp
=> iox-#743 Validation of request-response example

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/callbacks_in_c/ice_c_callbacks_subscriber.c, iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c, iceoryx_examples/icedelivery_in_c/README.md, iceoryx_examples/icedelivery_in_c/ice_c_subscriber.c, iceoryx_examples/icediscovery_in_c/README.md, iceoryx_examples/iceoptions/README.md, iceoryx_examples/request_response_in_c/README.md, iceoryx_examples/request_response_in_c/client_c_waitset.c
Signed-off-by: Michael Poehnl <michael.poehnl@apex.ai> …
=> iox-#743 example fixes 

iceoryx_examples/icehello/README.md
=> iox-#743 Validation of icehello example

iceoryx_examples/singleprocess/README.md, iceoryx_examples/singleprocess/single_process.cpp
=> iox-#743 review single process example

doc/website/concepts/best-practice-for-testing.md
=> iox-#743 Validation of Best Practice for Testing

doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md
=> iox-#743 Validation of "How optional and error values are returned in iceoryx"

iceoryx_examples/iceperf/README.md
=> iox-#743 Update iceperf readme

GOVERNANCE.md
=> iox-#743 Review Governance

doc/website/advanced/installation-guide-for-contributors.md
=> iox-#743 Validation of "Installation guide for contributors"

iceoryx_examples/callbacks/ice_callbacks_subscriber.cpp, iceoryx_examples/callbacks_in_c/README.md, iceoryx_examples/callbacks_in_c/ice_c_callbacks_subscriber.c, iceoryx_examples/callbacks_in_c/ice_c_callbacks_with_context_data.c, iceoryx_examples/icediscovery_in_c/README.md, iceoryx_examples/request_response/README.md, iceoryx_examples/request_response_in_c/README.md, iceoryx_examples/waitset_in_c/README.md, iceoryx_examples/waitset_in_c/ice_c_waitset_gateway.c, iceoryx_examples/waitset_in_c/ice_c_waitset_grouping.c, iceoryx_examples/waitset_in_c/ice_c_waitset_individual.c, iceoryx_examples/waitset_in_c/ice_c_waitset_timer_driven_execution.c
=> Iox #743 update waitset in c example

iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/handle_translator.hpp, iceoryx_hoofs/platform/win/source/handle_translator.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, tools/ci/build-test-windows.ps1
=> Iox #1264 threadsafe handle translator for windows

PLANNED_FEATURES.md
=> iox-#743 Update planned features

iceoryx_dds/README.md, tools/docker/Dockerfile, tools/docker/README.md, tools/iceoryx_build_test.sh
=> Iox #743 review tools docker

doc/website/concepts/how-optional-and-error-values-are-returned-in-iceoryx.md, iceoryx_dds/README.md, iceoryx_dds/examples/README.md
=> iox-#743 review iceoryx dds

doc/website/getting-started/overview.md
=> iox-#743 Validation of "Overview"

doc/goals-non-goals.md
=> Iox #743 update goals non goals.md

doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/ipc_handle_manager.hpp, iceoryx_hoofs/platform/win/source/ipc_handle_manager.cpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/platform/win/source/semaphore.cpp, iceoryx_hoofs/test/integrationtests/test_resizeable_lockfree_queue_stresstest.cpp
=> iox-#1271 Make semaphore/mutex creation threadsafe in windows platform

README.md
=> iox-#743 Update top level README.md

doc/website/getting-started/what-is-iceoryx.md
=> iox-#743 Validation of "What is iceoryx"

doc/website/concepts/qos-policies.md, doc/website/release-notes/iceoryx-v2-0-0.md, iceoryx_binding_c/include/iceoryx_binding_c/subscriber.h, iceoryx_examples/iceoptions/README.md, iceoryx_posh/include/iceoryx_posh/popo/subscriber_options.hpp, iceoryx_posh/source/roudi/port_manager.cpp, iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp, iceoryx_posh/test/moduletests/test_roudi_portmanager.cpp
=> Iox #1278 subscriber requesting history support should match with any history

doc/website/advanced/configuration-guide.md
=> iox-#743 Review configuration guide

doc/website/.pages, doc/website/getting-started/overview.md, doc/website/release-notes/.pages, doc/website/release-notes/iceoryx-v2-0-0.md
=> iox-#743 Fixes to make docs exportable (`master`)

iceoryx_examples/icecrystal/Readme.md, iceoryx_examples/icedelivery/README.md, iceoryx_examples/icediscovery/README.md, iceoryx_examples/icediscovery_in_c/README.md, iceoryx_examples/request_response/README.md, iceoryx_examples/request_response_in_c/README.md
=> iox-#743 Add links to new asciinema recordings (`v2.x`)

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_hoofs/test/moduletests/test_cxx_expected.cpp, iceoryx_hoofs/test/moduletests/test_relocatable_ptr.cpp, iceoryx_posh/test/integrationtests/test_popo_chunk_building_blocks.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp, iceoryx_posh/test/moduletests/test_popo_publisher_options.cpp, iceoryx_posh/test/moduletests/test_popo_server_options.cpp, iceoryx_posh/test/moduletests/test_popo_subscriber_options.cpp
=> iox-#1072 replace FAIL and SUCCEED with GTEST_FAIL and GTEST_SUCCEED

.github/workflows/lint_pull_request.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/optional.inl, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_types.cpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_types.hpp, iceoryx_hoofs/test/moduletests/test_cxx_optional.cpp
=> iox-#996 add functional interface to optional

iceoryx_hoofs/test/CMakeLists.txt, iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp, iceoryx_hoofs/test/mocktests/test_hoofs_mock.cpp, iceoryx_meta/tests.cmake, tools/ci/build-test-windows.ps1
=> iox-#1099 add test for error handler mock

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dds/source/gateway/main.cpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/filesystem.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp, iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder_pattern.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/filesystem.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/memory_map.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object/shared_memory.hpp, iceoryx_hoofs/source/cxx/filesystem.cpp, iceoryx_hoofs/source/posix_wrapper/named_pipe.cpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_hoofs/test/moduletests/test_shared_memory_object.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.hpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/runtime/shared_memory_user.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/posix_shm_memory_provider.hpp, iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp, iceoryx_posh/source/runtime/shared_memory_user.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp
=> Iox #1036 use builder pattern for shared memory

.github/workflows/build-test.yml, .github/workflows/changelog.yml, .github/workflows/lint_master.yml, .github/workflows/lint_pull_request.yml, .github/workflows/nightly.yml, .github/workflows/release_build_publish.yml, doc/website/release-notes/iceoryx-unreleased.md
=> Fix FreeBSD CI build

iceoryx_hoofs/CMakeLists.txt, iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake, iceoryx_hoofs/platform/CMakeLists.txt, iceoryx_hoofs/testing/CMakeLists.txt
Signed-off-by: Andre Nguyen <nguyen.apv@gmail.com>
[eca]: …
=> iox-#280 Split hoofs CMakeLists.txt into multiple folders

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
=> iox-#208 add insert method

README.md
Resolves issue #1352
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes
[eca]: …
=> iox-#1352 ADLINK is now ZettaScale Technology

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp, iceoryx_hoofs/test/moduletests/test_cxx_string.cpp
=> iox-#208 add append for char and std::string

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/test/integrationtests/test_service_discovery.cpp
1. [ ] Changelog updated [in the unreleased section][changelog] including API breaking changes …
=> Iox #1065 refactor service discovery tests

.github/workflows/build-test.yml, iceoryx_binding_c/test/CMakeLists.txt, iceoryx_hoofs/test/CMakeLists.txt, iceoryx_hoofs/test/moduletests/test_concurrent_fifo.cpp, iceoryx_posh/test/CMakeLists.txt, iceoryx_posh/test/moduletests/test_popo_chunk_distributor.cpp
=> iox-#1382 Fix build on FreeBSD

README.md
=> iox-#1387 Fix link to AVIN AUTOSAR Adaptive Platform

iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake
Signed-off-by: Linqing Liu <tsing.liu@autocore.ai>
[eca]: …
=> iox-#1401 add PRIVATE to target_compile_options on the QNX platform

.github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml, iceoryx_hoofs/source/file_reader/file_reader.cpp, iceoryx_posh/source/popo/ports/client_port_roudi.cpp
=> Iox #1394 Fix wrong default case handling

.github/workflows/lint_pull_request.yml, .lycheeignore, doc/website/release-notes/iceoryx-unreleased.md, tools/scripts/ice_env.sh
- [ x Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed) …
=> iox-#1410 ice-env.sh supports parallel docker containers

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/assignment.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/comparable.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/constructor.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/convertable.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/protected_constructor.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/newtype/sortable.hpp
=> iox-#1394 Prevent destruction of NewType derived classes by base class pointer

iceoryx_binding_c/test/moduletests/test_request_header.cpp, iceoryx_binding_c/test/moduletests/test_response_header.cpp, iceoryx_binding_c/test/moduletests/test_wait_set.cpp, iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp, iceoryx_hoofs/test/moduletests/test_concurrent_periodic_task.cpp, iceoryx_hoofs/test/moduletests/test_cxx_deadline_timer.cpp, iceoryx_posh/test/integrationtests/test_popo_port_user_building_blocks.cpp, iceoryx_posh/test/integrationtests/test_posh_mepoo.cpp, iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp, iceoryx_posh/test/moduletests/test_popo_listener.cpp, iceoryx_posh/test/moduletests/test_roudi_mempool_introspection.cpp
Add the missing test id into gtest case including TIMING_TEST_F and
TIMING_TEST_P. …
=> Iox #1125 Add unique test ids into gtest case including TIMING_TEST

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/newtype.hpp, iceoryx_hoofs/test/moduletests/test_cxx_newtype.cpp
=> iox-#1425 create convenience macro for newtype

iceoryx_hoofs/platform/win/include/iceoryx_hoofs/platform/pthread.hpp, iceoryx_hoofs/platform/win/source/pthread.cpp, iceoryx_hoofs/test/moduletests/test_posix_thread.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/shared_chunk.hpp, iceoryx_posh/include/iceoryx_posh/internal/popo/ports/base_port.hpp, iceoryx_posh/test/moduletests/test_mepoo_shared_chunk.cpp
=> iox-#1365 implement thread wrapper for windows

iceoryx_hoofs/include/iceoryx_hoofs/cxx/forward_list.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/forward_list.inl, iceoryx_hoofs/test/moduletests/test_cxx_forward_list.cpp
=> iox-#1196 fix forward list warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scoped_static.inl, iceoryx_hoofs/source/cxx/requires.cpp, iceoryx_hoofs/test/moduletests/test_cxx_type_traits.cpp
=> iox-#1196 Fix require, scoped_static, type_traits warnings

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/roudi/process_manager.cpp
=> iox-#1476 Replace single quotation mark with apostrophe

iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/fifo.inl, iceoryx_hoofs/test/moduletests/test_concurrent_fifo.cpp
=> iox-#1196 Fix warnings in FiFo

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/convert.inl
=> iox-#1196 Fix warnings in convert inl

.github/workflows/build-test.yml, tools/ci/build-test-freebsd.sh
=> iox-#1338 Optimize FreeBSD build

iceoryx_posh/source/runtime/ipc_interface_base.cpp
=> iox-#1482 add IpcInterfaceBase::openIpcChannel error info

iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/taco.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/taco.inl, iceoryx_hoofs/test/moduletests/test_concurrent_taco.cpp
=> iox-#1196 fix taco warnings

.clang-tidy, iceoryx_hoofs/include/iceoryx_hoofs/concurrent/lockfree_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/concurrent/resizeable_lockfree_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/buffer.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/cyclic_index.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/index_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/index_queue.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/lockfree_queue.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl, iceoryx_hoofs/test/moduletests/test_index_queue.cpp, iceoryx_hoofs/test/moduletests/test_lockfree_queue.cpp, iceoryx_hoofs/test/moduletests/test_lockfree_queue_buffer.cpp, iceoryx_hoofs/test/moduletests/test_lockfree_queue_cyclic_index.cpp, iceoryx_hoofs/test/moduletests/test_resizeable_lockfree_queue.cpp
=> Iox #1196 fix lockfree queue warnings

doc/website/release-notes/.pages, doc/website/release-notes/iceoryx-v2-0-3.md, iceoryx_posh/source/roudi/process_manager.cpp
=> iox-#1476 Replace single quotation mark with apostrophe [release_2.0]

iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/system_configuration.hpp, iceoryx_hoofs/include/iceoryx_hoofs/posix_wrapper/thread.hpp, iceoryx_hoofs/source/posix_wrapper/thread.cpp, iceoryx_hoofs/test/moduletests/test_posix_thread.cpp
=> iox-#1196 Fix warnings in thread and system configuration

iceoryx_hoofs/include/iceoryx_hoofs/cxx/requires.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/file_reader/file_reader.hpp, iceoryx_hoofs/source/file_reader/file_reader.cpp, iceoryx_hoofs/test/moduletests/test_file_reader.cpp
=> iox-#1196 fix file reader warnings

CONTRIBUTING.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/access_control.hpp, iceoryx_hoofs/source/posix_wrapper/access_control.cpp, iceoryx_hoofs/test/moduletests/test_access_control.cpp
=> iox-#1196 Fix warnings in access control

iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-#1196 Fix clang-tidy and some AUTOSAR warnings in `cxx::vector`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/cmake/IceoryxPackageHelper.cmake, iceoryx_posh/CMakeLists.txt
=> iox-#1528 Fix usage of testing libs in source tree builds

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, doc/website/release-notes/iceoryx-unreleased.md, tools/git-hooks/Readme.md, tools/git-hooks/prepare-commit-msg
=> Iox 1530 remove hash from branch names

.github/actions/install-iceoryx-deps-and-clang/action.yml, .github/workflows/lint_pull_request.yml, .github/workflows/nightly.yml
=> iox-#1196 activate full clang-tidy nightly scan

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl
=> iox-#1196 Suppress clang-tidy and AUTOSAR warnings in `PointerRepository`

iceoryx_hoofs/source/cxx/deadline_timer.cpp
=> iox-#1394 Fix AUTOSAR violations in DeadlineTimer

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.inl
=> iox-#1551 add inline keyword to inline methods

.github/actions/install-iceoryx-deps-and-clang/action.yml, .github/workflows/build-test.yml, doc/website/concepts/best-practice-for-testing.md
=> Iox 1196 fix LLVM installation in GitHub CI

.clang-tidy-diff-scans.txt, PLANNED_FEATURES.md, README.md, iceoryx_binding_c/test/moduletests/test_listener.cpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/base_relative_pointer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/pointer_repository.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/relocatable_pointer/relative_pointer.inl, iceoryx_hoofs/source/relocatable_pointer/base_relative_pointer.cpp, iceoryx_hoofs/test/moduletests/test_relative_pointer.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp, iceoryx_posh/source/mepoo/shm_safe_unmanaged_chunk.cpp, iceoryx_posh/source/roudi/memory/memory_provider.cpp, iceoryx_posh/source/roudi/process_manager.cpp, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/source/runtime/shared_memory_user.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_provider.cpp
=> iox-#1196 Fix clang-tidy warnings in `RelativePointer`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_examples/iceperf/uds.cpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/source/log/logger.cpp, iceoryx_hoofs/source/log/logmanager.cpp, iceoryx_hoofs/test/moduletests/test_cxx_helplets.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/listener.inl, iceoryx_posh/include/iceoryx_posh/version/version_info.hpp, iceoryx_posh/source/gateway/toml_gateway_config_parser.cpp, iceoryx_posh/source/roudi/application/roudi_main.cpp, iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
=> iox-#1560 remove rarely used functions from helplets and refactor strlen2

iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/builder.hpp
=> iox-#1394 Fix last Axivion warning in builder

.github/actions/install-iceoryx-deps-and-clang/action.yml
=> iox-#1576 Use clang-tidy 15

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string_internal.hpp
=> iox-#1394 fix axivion reported violations for string_internal.hpp

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
=> iox-#1594 Pass `CleanupCapacity` to underlying `cxx::function` in `ScopeGuard`

iceoryx_hoofs/include/iceoryx_hoofs/cxx/scope_guard.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/scope_guard.inl
=> iox-#1394 Fix AUTOSAR violations in ScopeGuard

.github/workflows/build-test.yml
=> iox-#1625 Use major tag in freebsd ci script

doc/website/release-notes/iceoryx-unreleased.md
=> iox-#1619 iceoryx_platform PART 4: release notes for new iceoryx_platform package

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/optional.inl
=> iox-#1638 Correct access of m_data in optional

doc/design/chunk_header.md
Signed-off-by: deneschen <deneschen@foxmail.com>
1. [x] Assign PR to …
=> iox-#1624 Fix typo

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/stack.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl, iceoryx_hoofs/test/moduletests/test_cxx_stack.cpp
=> iox-1469 implement copy and move operations for stack

.clang-tidy-diff-scans.txt, iceoryx_hoofs/include/iceoryx_hoofs/log/logstream.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/platform/logger.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/console_logger.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logcommon.hpp, iceoryx_hoofs/include/iceoryx_hoofs/log/platform_building_blocks/logger.hpp, iceoryx_hoofs/source/log/platform_building_blocks/logger.cpp, iceoryx_hoofs/test/moduletests/test_console_logger.cpp, iceoryx_hoofs/test/moduletests/test_cxx_filesystem.cpp, iceoryx_hoofs/test/moduletests/test_logging.cpp, iceoryx_hoofs/test/moduletests/test_logstream.cpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/logger.hpp, iceoryx_hoofs/testing/include/iceoryx_hoofs/testing/mocks/logger_mock.hpp, iceoryx_hoofs/testing/logger.cpp, iceoryx_posh/test/moduletests/test_capro_service.cpp, iceoryx_posh/test/moduletests/test_compatibility_check_level.cpp, iceoryx_posh/test/moduletests/test_mepoo_memory_manager.cpp, iceoryx_posh/test/moduletests/test_monitoringmode_logstream.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_receiver.cpp, iceoryx_posh/test/moduletests/test_popo_chunk_sender.cpp, iceoryx_posh/test/moduletests/test_popo_client_port.cpp, iceoryx_posh/test/moduletests/test_popo_server_port_user.cpp, iceoryx_posh/test/moduletests/test_roudi_memory_manager.cpp
=> Iox-#1345 Add doxygen documentation to logger classes [Stacked PR 4]

iceoryx_hoofs/test/moduletests/test_logging.cpp
=> iox-#1345 Refactor parameterized tests

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/gateway/gateway_generic.inl
=> iox-#1666 Fix GatewayGeneric running state variable setting

doc/website/release-notes/iceoryx-unreleased.md
=> iox-#1345 Update release notes for logger

iceoryx_hoofs/include/iceoryx_hoofs/cxx/unique_ptr.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
=> iox-1394 Fix AUTOSAR warnings for `unique_ptr`

iceoryx_hoofs/include/iceoryx_hoofs/cxx/type_traits.hpp
=> iox-#1394-fix-axivion-violation-for-type_traits_hpp

iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp
=> iox-#1704 Remove explicit includes of `function_ref`

iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/unique_ptr.inl
=> iox-1394 Address last AUTOSAR finding in `unique_ptr`

iceoryx_hoofs/test/stresstests/BUILD.bazel
=> iox-#1547 Add ldl to linkopts for stresstest in Bazel

iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/optional.inl, iceoryx_hoofs/test/mocktests/test_error_handler_mock.cpp, iceoryx_hoofs/test/moduletests/test_cxx_optional.cpp, iceoryx_hoofs/test/moduletests/test_cxx_stack.cpp
- [ x Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed) …
=> Iox #1394 fix axivion violation for optional hpp inl

.github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml, .lycheeignore
1. ~[ ] Changelog updated [in the unreleased section][changelog] including API breaking changes~ …
=> iox-#1781 Update CI actions to fix warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/string.inl
=> iox #1394 fix axivion violation for string

iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/memory/pointer_repository.inl
=> iox-#1394 Fix AUTOSAR violations in PointerRepository

iceoryx_dust/test/moduletests/test_cli_command_line_argument_definition.cpp, iceoryx_dust/test/moduletests/test_cli_command_line_parser.cpp
=> iox-#1798 Fix float comparision tests for cmd line parser

.github/workflows/lint_pull_request.yml, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl
=> Iox 1781 fix ci warnings

iceoryx_hoofs/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/expected.inl
=> Iox #1394 fix axivion violation for expected hpp inl

iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp
=> iox-#1394-fix-axivion-violation-for-vector

iceoryx_hoofs/container/include/iox/uninitialized_array.hpp
1. [ ] Add sensible notes for the reviewer
1. [x] Assign …
=> iox-#1394-fix-axivion-violation-for-uninitialized_array

iceoryx_hoofs/include/iceoryx_hoofs/cxx/helplets.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/helplets.inl
1. [ ] Add sensible notes for the reviewer
1. [x] Assign …
=> iox-#1394-fix-axivion-violation-for-helplets

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/source/roudi/roudi_config_toml_file_provider.cpp
=> iox-#1826 Use default roudi config file

iceoryx_hoofs/include/iceoryx_hoofs/cxx/serialization.hpp, iceoryx_hoofs/include/iceoryx_hoofs/design_pattern/creation.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/periodic_task.hpp, iceoryx_hoofs/test/moduletests/test_cxx_functional_interface_common.hpp
=> iox-#1394 Replace back-tick with single quote in hoofs

iceoryx_hoofs/test/stresstests/test_lockfree_queue_stresstest.cpp
=> iox-#1835 updated monotonic naming

iceoryx_hoofs/source/posix_wrapper/unix_domain_socket.cpp
=> Fixed typo in unix_domain_socket.cpp error message

.github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml
=> iox-#1781 Fix CI warnings regarding GCC, changed files and links

iceoryx_hoofs/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/iceoryx_hoofs_types.inl
Signed-off-by: Ibrahim Kuru <ibrahim.kuru@apex.ai>
1. [x] Assign PR …
=> iox-#1394 Fix-axivion-violations-for-iceoryx_hoofs_types_hpp

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/attributes.hpp, iceoryx_platform/linux/include/iceoryx_platform/attributes.hpp, iceoryx_platform/mac/include/iceoryx_platform/attributes.hpp, iceoryx_platform/qnx/include/iceoryx_platform/attributes.hpp, iceoryx_platform/unix/include/iceoryx_platform/attributes.hpp, iceoryx_platform/win/include/iceoryx_platform/attributes.hpp
=> iox-1726 Move some attributes to `iceoryx_platform`

iceoryx_hoofs/vocabulary/include/iox/detail/string.inl
Signed-off-by: Jeff Ithier <jeff.ithier@apex.ai>
1. [x] Assign PR …
=> iox-#1756 Use iceoryx logger in string.inl

iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp
=> iox-#1394 Fix axivion warnings in "string_internal.hpp"

doc/design/command-line-parser.md, iceoryx_dust/include/iceoryx_dust/posix_wrapper/message_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/test/.clang-tidy, iceoryx_hoofs/test/moduletests/test_cxx_convert.cpp, iceoryx_hoofs/test/moduletests/test_vocabulary_string.cpp, iceoryx_hoofs/vocabulary/include/iox/detail/string.inl, iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp, iceoryx_hoofs/vocabulary/include/iox/detail/string_type_traits.hpp, iceoryx_hoofs/vocabulary/include/iox/string.hpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/popo/publisher_options.hpp
=> iox-1391 Minor fixes related to namespace change

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/test/moduletests/test_cxx_vector.cpp
=> iox-#1871 Fix aggressive loop optimizations error with gcc9.4 

iceoryx_hoofs/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/stack.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/vector.inl
=> Fix warnings in buffer and container modules

README.md, doc/website/getting-started/what-is-iceoryx.md
=> iox-#1872 Update Framework References in Documentation

iceoryx_hoofs/buffer/include/iox/detail/stack.inl, iceoryx_hoofs/container/include/iox/detail/vector.inl
1. [ ] ~~Tests follow the [best practice for testing][testing]~~
1. [ ] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [ ] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~ …
=> Fix more warnings in vector.inl & stack.inl

iceoryx_hoofs/container/include/iox/uninitialized_array.hpp, iceoryx_hoofs/container/include/iox/vector.hpp
Signed-off-by: Jeff Ithier <jeff.ithier@apex.ai>
1. [ ] ~~Tests follow the [best practice for testing][testing]~~
1. [ ] ~~Changelog updated [in the unreleased section][changelog] including API breaking changes~~
1. [ ] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~
1. [x] …
=> Fix more warnings in vector.hpp & uninitialized_array.hpp

iceoryx_binding_c/include/iceoryx_binding_c/log.h
=> iox-#1904 Restore Binding C API compatibility with v2

doc/design/determinism.md, iceoryx_hoofs/buffer/include/iox/stack.hpp, iceoryx_hoofs/container/include/iox/uninitialized_array.hpp, iceoryx_hoofs/container/include/iox/vector.hpp
=> Iox 1815 add determinism label to selected types

iceoryx_hoofs/vocabulary/include/iox/detail/string.inl, iceoryx_hoofs/vocabulary/include/iox/detail/string_internal.hpp, iceoryx_hoofs/vocabulary/include/iox/string.hpp
=> iox-#1394 Fix Axivion warnings in 'string'

.github/workflows/build-test.yml
This refers to https://github.com/ros-tooling/setup-ros/pull/543
The package installation of `grub-efi-amd64-signed` in the GitHub Action from https://github.com/ros-tooling/setup-ros.
This causes an hard error for updating APT for ROS 2. Holding back the package from installation will solve this temporally.
- [ x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
- …
=> iox-#1906 Update ROS 2 Action to v0.6 for fixing APT issue

iceoryx_hoofs/test/moduletests/test_container_uninitialized_array.cpp, iceoryx_hoofs/test/moduletests/test_container_vector.cpp
=> iox-#1913 Add missing test cases for vector and UninitializedArray

iceoryx_hoofs/container/include/iox/detail/vector.inl, iceoryx_hoofs/design/include/iox/detail/functional_interface.inl, iceoryx_hoofs/filesystem/include/iox/detail/filesystem.inl, iceoryx_hoofs/functional/include/iox/detail/function_ref.inl, iceoryx_hoofs/functional/include/iox/detail/storable_function.inl, iceoryx_hoofs/memory/include/iox/detail/relative_pointer.inl, iceoryx_hoofs/memory/include/iox/detail/scoped_static.inl, iceoryx_hoofs/primitives/include/iox/type_traits.hpp, iceoryx_hoofs/vocabulary/include/iox/detail/string.inl, iceoryx_hoofs/vocabulary/include/iox/string.hpp
=> iox-#1394 fix axivion warnings for multiple files part 3

doc/website/release-notes/iceoryx-unreleased.md, tools/introspection/include/iceoryx_introspection/introspection_app.hpp, tools/introspection/source/introspection_app.cpp
=> Introspection-app Wrap c calls in posixCall

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/source/log/building_blocks/console_logger.cpp
=> iox-1932 Fix log timestamp conversion

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/include/iceoryx_dust/cxx/std_string_support.hpp, iceoryx_dust/include/iceoryx_dust/internal/cxx/std_string_support.inl, iceoryx_dust/test/moduletests/test_cxx_string_conversion.cpp
=> iox-#1612 add string convertion with optional

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/smart_lock.inl, iceoryx_hoofs/test/moduletests/test_concurrent_smart_lock.cpp
=> iox-#1966 implement dereference operator

iceoryx_dust/source/posix_wrapper/named_pipe.cpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/posix_wrapper/shared_memory_object.hpp, iceoryx_hoofs/source/posix_wrapper/shared_memory_object.cpp, iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp
=> iox-#1971 Remove allocator from shared memory object

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/capro/service_description.hpp
=> iox-#1977 ServiceDescription Interfaces and INTERFACE_NAMES do not match

iceoryx_posh/source/roudi/port_manager.cpp
=> iox-#1908 resolve the issue when the iox-roudi working with gateways

bazel/cpptoml/repositories.bzl
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~ …
=> Use Label when loading cpptoml

.github/workflows/lint_pull_request.yml, doc/website/release-notes/iceoryx-unreleased.md
=> iox-#1982 Update release notes for FreeRTOS support

iceoryx_examples/iceperf/iceperf_leader.cpp
=> iox-#2003 Make iceperf memory size output human readable

GOVERNANCE.md
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~ …
=> iox-#2007 Adapt docs with new meetup cadence

.github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml, iceoryx_examples/complexdata/topic_data.hpp, iceoryx_hoofs/container/include/iox/detail/list.inl, iceoryx_hoofs/container/include/iox/list.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/list.hpp, iceoryx_hoofs/test/moduletests/test_cxx_list.cpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/process_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/process_manager.hpp, iceoryx_posh/test/integrationtests/test_publisher_subscriber_communication.cpp
=> [Stacked on #2059] iox-#1391 Move list to container module

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/lockfree_queue.inl, iceoryx_hoofs/include/iceoryx_hoofs/internal/concurrent/lockfree_queue/resizeable_lockfree_queue.inl, iceoryx_hoofs/test/moduletests/test_concurrent_lockfree_queue.cpp
=> iox-#2067 Support move-only types in the LockFreeQueue

.cirrus.yaml, .github/workflows/build-test.yml, README.md, iceoryx_hoofs/include/iceoryx_hoofs/cxx/variant_queue.hpp, iceoryx_hoofs/include/iceoryx_hoofs/internal/cxx/variant_queue.inl, iceoryx_hoofs/test/moduletests/test_cxx_variant_queue.cpp, iceoryx_hoofs/test/moduletests/test_posix_shared_memory_object.cpp, tools/ci/docker/archlinux-base-devel, tools/ci/docker/ubuntu-22.04, tools/iceoryx_build_test.sh, tools/scripts/add_test_users.sh
=> iox-#2070 Move FreeBSD build to Cirrus CI and add aarch64 and Arch Linux builds

.github/PULL_REQUEST_TEMPLATE.md
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to `./clang-tidy-diff-scans.txt`~~ …
=> Adapt PR template to reduced number of reviewers

.cirrus.yaml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_dust/container/include/iox/fixed_position_container.hpp, tools/ci/docker/archlinux-base-devel
=> iox-#2084 Fix qnx build and setup CI for gcc 8.3

GOVERNANCE.md
=> iox-#2007 Update developer meetup info

.github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/functional/include/iox/detail/function_ref.inl, iceoryx_hoofs/memory/include/iox/detail/scope_guard.inl, iceoryx_hoofs/memory/include/iox/scope_guard.hpp, iceoryx_hoofs/posix/time/include/iox/detail/adaptive_wait.hpp, iceoryx_hoofs/posix/time/source/adaptive_wait.cpp, iceoryx_hoofs/test/moduletests/test_container_list.cpp, iceoryx_hoofs/test/moduletests/test_functional_function_ref.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/building_blocks/condition_listener.hpp, iceoryx_posh/include/iceoryx_posh/runtime/service_discovery.hpp, iceoryx_posh/source/popo/building_blocks/condition_listener.cpp, iceoryx_posh/source/runtime/service_discovery.cpp, iceoryx_posh/test/moduletests/test_popo_condition_variable.cpp
=> iox-#2060 Fix clang tidy warning from full scan

tools/introspection/CMakeLists.txt, tools/introspection/package.xml
1. [x] ~~Add a second reviewer for complex new features or larger refactorings~~
1. [x] ~~All touched (C/C++) source code files from `iceoryx_hoofs` are added to …
=> Forward port changes from release `2.x` to `master`

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/concurrent/buffer/source/mpmc_loffli.cpp, iceoryx_posh/include/iceoryx_posh/internal/popo/used_chunk_list.inl
=> iox-#2196 Fix memory order in 'MpmcLoFFLi' fence synchronization

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/test/moduletests/test_runtime.cpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.hpp, iceoryx_posh/include/iceoryx_posh/iceoryx_posh_types.inl, iceoryx_posh/include/iceoryx_posh/internal/mepoo/mepoo_segment.inl, iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_base.hpp, iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_creator.hpp, iceoryx_posh/include/iceoryx_posh/internal/runtime/ipc_interface_user.hpp, iceoryx_posh/include/iceoryx_posh/internal/runtime/posh_runtime_impl.hpp, iceoryx_posh/include/iceoryx_posh/roudi/memory/iceoryx_roudi_memory_manager.hpp, iceoryx_posh/source/roudi/memory/iceoryx_roudi_memory_manager.cpp, iceoryx_posh/source/roudi/memory/posix_shm_memory_provider.cpp, iceoryx_posh/source/roudi/process.cpp, iceoryx_posh/source/roudi/roudi.cpp, iceoryx_posh/source/runtime/ipc_interface_base.cpp, iceoryx_posh/source/runtime/ipc_interface_creator.cpp, iceoryx_posh/source/runtime/ipc_interface_user.cpp, iceoryx_posh/source/runtime/ipc_runtime_interface.cpp, iceoryx_posh/source/runtime/posh_runtime_impl.cpp, iceoryx_posh/source/runtime/shared_memory_user.cpp, iceoryx_posh/test/integrationtests/test_mq_interface_startup_race.cpp, iceoryx_posh/test/moduletests/test_mepoo_segment.cpp, iceoryx_posh/test/moduletests/test_posh_runtime.cpp, iceoryx_posh/test/moduletests/test_posh_types.cpp, iceoryx_posh/test/moduletests/test_roudi_posix_shm_memory_provider.cpp, iceoryx_posh/test/moduletests/test_roudi_process_manager.cpp, iceoryx_posh/test/moduletests/test_runtime_ipc_interface.cpp, iceoryx_posh/test/moduletests/test_runtime_ipc_interface_creator.cpp
=> iox-#2185 Use prefix for iceoryx resources

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/attributes.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/deadline_timer.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/expected.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/filesystem.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/function.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/function_ref.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/functional_interface.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/list.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/newtype.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/optional.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/requires.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/scope_guard.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/scoped_static.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/stack.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/string.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/type_traits.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/unique_ptr.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/variant.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/cxx/vector.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/iceoryx_hoofs_types.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/file_lock.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/posix_access_rights.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/posix_call.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/signal_handler.hpp, iceoryx_hoofs/legacy/include/iceoryx_hoofs/posix_wrapper/thread.hpp, iceoryx_platform/freertos/include/iceoryx_platform/platform_settings.hpp, iceoryx_posh/source/mepoo/chunk_settings.cpp
=> iox-#1391 Update release notes and deprecate legacy namespaces

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_fifo.hpp, iceoryx_hoofs/concurrent/buffer/include/iox/detail/spsc_fifo.inl
=> iox-#2167 Update FiFo

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build-test.yml, .github/workflows/lint_pull_request.yml
=> iox-#2011 Update templates and actions

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/BUILD.bazel, iceoryx_hoofs/cmake/IceoryxHoofsDeployment.cmake, iceoryx_hoofs/cmake/iceoryx_hoofs_deployment.hpp.in, iceoryx_hoofs/posix/utility/include/iox/detail/system_configuration.hpp, iceoryx_meta/build_options.cmake
=> iox-#562 Deactivate 32-bit builds by default

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/posix/design/include/iox/detail/posix_call.inl, iceoryx_hoofs/posix/design/include/iox/posix_call.hpp, iceoryx_platform/generic/include/iceoryx_platform/generic/string.hpp, iceoryx_platform/generic/include/iceoryx_platform/string.hpp, iceoryx_platform/generic/source/string.cpp, iceoryx_platform/test/moduletests/test_platform_string.cpp, iceoryx_platform/win/include/iceoryx_platform/override/string.hpp, iceoryx_platform/win/include/iceoryx_platform/platform_correction.hpp, iceoryx_platform/win/source/string.cpp
This PR unifies the `strerror_r` behavior in the platform layer.
[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages …
=> iox-#1616 Handle 'strerror_r' idiosyncrasies in the platform layer

.github/workflows/build-test.yml, doc/website/release-notes/iceoryx-unreleased.md
Update github actions to fix deprecation warnings and fix FreeBSD job. …
=> iox-#2011 Update github actions

iceoryx_platform/generic/source/_string.cpp
=> iox-#2011 Fix clang-tidy on nightly builds

doc/website/FAQ.md
=> iox-#2287 Add faq shm size docker entry

iceoryx_binding_c/cmake/iceoryx_binding_cConfigVersion.cmake, iceoryx_hoofs/cmake/iceoryx_hoofsConfigVersion.cmake, iceoryx_platform/cmake/iceoryx_platformConfigVersion.cmake, iceoryx_posh/cmake/iceoryx_poshConfigVersion.cmake, tools/introspection/cmake/iceoryx_introspectionConfigVersion.cmake
This PR makes it possible to use `find_package(iceoryx_hoofs 2.95.0 REQUIRED)` in in-tree builds. …
=> iox-#1295 Make iceoryx version available for in-tree builds

.bazelrc, .gitignore
=> iox-#2011 Properly deactivate bzlmod

.clang-tidy-diff-scans.txt, doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/concurrent/sync/include/iox/atomic.hpp, iceoryx_platform/BUILD.bazel, iceoryx_platform/CMakeLists.txt, iceoryx_platform/generic/include/iceoryx_platform/atomic.hpp, iceoryx_platform/test/moduletests/test_platform_atomic.cpp, tools/scripts/clang_tidy_check.sh
This PR adds the `iox::Atomic` as drop-in replacement for the std::atomic. The std::atomic will be replaced in a follow up PR. …
=> iox-#2329 Add iox::Atomic

bazel/configure_version.bzl, doc/website/release-notes/iceoryx-unreleased.md
=> iox-#2345 fix bazel script to make macos bazel build successful

.cirrus.yaml
We ran out of compute credits for Cirrus CI for this month -> deactivate Cirrus CI …
=> iox-#2011 Deactivate Cirrus Ci for now

BUILD.bazel, doc/website/release-notes/iceoryx-unreleased.md
iox-#2368: Add `//:iceoryx` alias
[eca]: …
=> iox-#2368: Add `//:iceoryx` alias

MODULE.bazel
Update ncurses to https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/ncurses/6.4.20221231.bcr.4 to fix `(10:51:19) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/85354f712160bb81ff8d5fbef6e0ccfd/external/iceoryx+/tools/introspection/BUILD.bazel:19:11: no such target '@@ncurses+//:ncurses': target 'ncurses' not declared in package '' defined by /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/85354f712160bb81ff8d5fbef6e0ccfd/external/ncurses+/BUILD.bazel; however, a source directory of this name exists.  (Perhaps add 'exports_files(["ncurses"])' to /BUILD, or define a filegroup?) and referenced by '@@iceoryx+//tools/introspection:iceoryx_introspection'`
Holding off with Changelog update to avoid merge conflict
1. [x] Code follows the …
=> iox-#2438: Update ncurses

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.hpp, iceoryx_posh/include/iceoryx_posh/internal/roudi/introspection/port_introspection.inl, iceoryx_posh/include/iceoryx_posh/roudi/introspection_types.hpp, iceoryx_posh/test/moduletests/test_roudi_port_introspection.cpp
=> iox-#2076 Implement pub/sub options in introspection

.github/workflows/build-test.yml, doc/website/advanced/configuration-guide.md, doc/website/release-notes/iceoryx-unreleased.md, tools/ci/build-test-hoofs-subset.sh
This PR adds documentation and CI for the iceoryx_hoofs subset for iceoryx2. …
=> iox-#2457 Add documentation and CI for hoofs subset

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_binding_c/source/c_runtime.cpp, iceoryx_posh/experimental/include/iox/posh/experimental/node.hpp, iceoryx_posh/experimental/source/node.cpp, iceoryx_posh/roudi_env/source/minimal_iceoryx_config.cpp, iceoryx_posh/roudi_env/source/roudi_env_node_builder.cpp, iceoryx_posh/source/roudi/memory/roudi_memory_manager.cpp
This PR enhances code quality and safety across multiple core components of iceoryx. The changes focus on improving parameter validation, error handling, and constructor patterns while maintaining backward compatibility.
- Replace IOX_BUILDER_PARAMETER macro with manual implementation
- Add roudi_registration_timeout method and member variable
- Move doxygen comments to shares_address_space_with_roudi method
- Add comprehensive parameter documentation with @param[in] value
- Update copyright notices to LG Electronics Inc. in modified files
- Replace graceful error handling with IOX_ASSERT for invariant checking
- Enhanced parameter validation with proper assertion mechanisms
- Improved memory safety checks in RouDiMemoryManager
- Strengthened configuration validation in …
=> iox-#2469 improve code quality and safety (update)

doc/website/release-notes/iceoryx-unreleased.md, iceoryx_hoofs/reporting/source/console_logger.cpp, iceoryx_integrationtest/iceoryx_integrationtest/test_callback_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_callback_in_c_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_complexdata_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_experimental_node_publish_subscribe.py, iceoryx_integrationtest/iceoryx_integrationtest/test_experimental_node_request_response.py, iceoryx_integrationtest/iceoryx_integrationtest/test_ice_access_control_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icedelivery_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icedelivery_in_c_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_in_c_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icediscovery_monitoring.py, iceoryx_integrationtest/iceoryx_integrationtest/test_icehello_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_iceoptions_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_request_response_basic.py, iceoryx_integrationtest/iceoryx_integrationtest/test_request_response_in_c_basic.py, iceoryx_integrationtest/iceoryx_integrationtest/test_request_response_in_c_listener_and_waitset.py, iceoryx_integrationtest/iceoryx_integrationtest/test_request_response_listener.py, iceoryx_integrationtest/iceoryx_integrationtest/test_request_response_untyped.py, iceoryx_integrationtest/iceoryx_integrationtest/test_roudi_startup_shutdown.py, iceoryx_integrationtest/iceoryx_integrationtest/test_singleprocess_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_user_header_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_example.py, iceoryx_integrationtest/iceoryx_integrationtest/test_waitset_in_c_example.py
=> iox-#2478 Console Logs should be output to stderr
